'''Dictionaries for standardising ROI labels of head-and-neck cohort.'''

head_and_neck_plan = {}
head_and_neck_plan['bolus'] = [
    '0.5CM BOLUS',
    '0.5CM BOLUS',
    'Bolus',
    'Bolus',
    'bolus required',
    'bolus required',
    'for bol',
    'for bolus',
    'for bolus',
    'For Bolus',
    'For Bolus',
    'for virtual bolus',
    'for virtual bolus',
    'Plan Bolus',
    'Plan Bolus',
    'Planning  Bolus',
    'Planning  Bolus',
    'Planning blous',
    'planning bolus',
    'planning bolus',
    'PLANNING BOLUS',
    'PLANNING BOLUS',
    'planning Bolus',
    'planning Bolus',
    'Planning Bolus',
    'Planning Bolus',
    'Planning bolus',
    'Planning bolus',
    'planningbolus',
    'planningbolus',
    'Planningbolus',
    'Planningbolus',
    'Planningl bolus',
    'Planningl bolus',
    'PRETEND BOLUS',
    'PRETEND BOLUS',
    'pretend bolus',
    'pretend bolus',
    'Pretend bolus',
    'Pretend bolus',
    'Pretend Bolus',
    'Pretend Bolus',
    'tbol',
    'TREATMENT BOLUS',
    'TREATMENT BOLUS',
    'Treatment bolus',
    'Treatment bolus',
    'virtual bolus',
    'virtual bolus',
    'VIRTUAL BOLUS',
    'VIRTUAL BOLUS',
    'Virtual bolus',
    'Virtual bolus',
    'Virtual Bolus',
    'Virtual Bolus']
head_and_neck_plan['brainstem'] = [
    'B stem',
    'b stem',
    'B Stem',
    'B stem PRV',
    'b stem PRV',
    'b stemPRV',
    'B StemPRV',
    'B stemPRV',
    'brain stem',
    'Brain stem',
    'Brain Stem',
    'Brain Stem PRV',
    'Brain stem prv',
    'brain stem PRV',
    'Brain stem PRV',
    'brain stem prv',
    'Brain stemprv',
    'brain stemPRV',
    'Brain stemPRV',
    'brainstem',
    'Brainstem',
    'BRAINSTEM',
    'Brainstem b',
    'brainstem PRV',
    'BrainStem PRV',
    'brainstem prv',
    'BRAINSTEM PRV',
    'Brainstem PRV',
    'Brainstem prv',
    'BRAINSTEM_',
    'BRAINSTEM_PRV',
    'BRAINSTEM_SP',
    'BRAINSTEM_SP PRV',
    'BrainstemPRV',
    'brainstemPRV',
    'brainstemsjj',
    'Brrainstem PRV',
    'Brsinstem',
    'bstem',
    'PRV b stem',
    'PRV B stem',
    'PRV Brain Stem',
    'PRV Brain stem',
    'PRV BRAIN STEM',
    'PRV brain stem',
    'PRV brainstem',
    'PRV BRAINSTEM',
    'PRV Brainstem',
    'PRV bstem',
    'PRV Bstem',
    'PRV stem',
    'PRVBrainstem',
    'PRVbrainstem',
    'Stem PRV',
    'StemPRV']
head_and_neck_plan['cochlea_left'] = [
    'Cochlea L',
    'cochlea L',
    'Cochlea L OPT',
    'cochlea L PRV',
    'Cochlea left',
    'Cochlea Lt',
    'COCHLEA_L',
    'COCHLEA_L OPT',
    'COCHLEA_L PS',
    'COCHLEA_L_edited',
    'COCHLEA_L_opt',
    'COCHLEA_L_Opt',
    'COCHLEA_L_OPT',
    'COCHLEA_L_PS',
    'COCHLEA_L_SP',
    'COCHLEA_L_SP OPT',
    'COCHLEA_L_SP opt',
    'L Cochlea',
    'L cochlea',
    'l cochlea',
    'L cochlea opt',
    'L cochlea OPT',
    'l cochlea OPT',
    'l cochlea opt',
    'L Cochlea Opt',
    'L Cochlea OPT',
    'L cochlea PRV',
    'l cochlea PRV',
    'l cochlea ps',
    'L cochlea PS',
    'L cochlea ps',
    'l cochlea PS',
    'L cochlea2',
    'l cochleaOPT',
    'L CochleaPRV',
    'l cochlear',
    'L cochlear',
    'L cochlear Opt',
    'L cochlear opt',
    'L cochlear ps',
    'L cochlear PS',
    'L Cochlear SLD',
    'l cochlearOPT',
    'lcochlea',
    'lcochlea OPT',
    'left cochlea',
    'Left cochlea',
    'left cochlea OPT',
    'Left cochlea OPT',
    'left cochlea PS',
    'lt cochlea',
    'Lt Cochlea',
    'LT COCHLEA OPT',
    'Lt Cochlea Opt',
    'Lt Cochlea PRV',
    'lt cochlea PRV',
    'Lt OPT Cochlea',
    'OPT L cochlea',
    'OPT left cochlea',
    'OPT Lt cochlea',
    'OPT Lt Cochlea',
    'PRV l cochlea',
    'PRV L COCHLEA',
    'PRV L Cochlea',
    'PRV LCochlea',
    'PRV Lcochlea',
    'PRV LtCochlea',
    'PS Cochlea left',
    'PScochlealeft']
head_and_neck_plan['cochlea_right'] = [
    'Cochlea R',
    'Cochlea R OPT',
    'Cochlea right',
    'COCHLEA RIGHT',
    'Cochlea Rt',
    'COCHLEA_R',
    'COCHLEA_R Opt',
    'COCHLEA_R OPT',
    'COCHLEA_R PS',
    'COCHLEA_R_edited',
    'COCHLEA_R_opt',
    'COCHLEA_R_OPT',
    'COCHLEA_R_PS',
    'COCHLEA_R_SP',
    'COCHLEA_R_SP opt',
    'COCHLEA_R_SP OPT',
    'OPT R cochlea',
    'OPT right cochlea',
    'OPT Rt cochlea',
    'OPT Rt Cochlea',
    'PRV R Cochlea',
    'PRV R COCHLEA',
    'PRV Rcochlea',
    'PRV RCochlea',
    'PRV Rt Cochlea',
    'PRV RtCochlea',
    'PS Cochlea right',
    'PSCochleaRight',
    'r cochlea',
    'R cochlea',
    'R Cochlea',
    'R cochlea OPT',
    'R Cochlea Opt',
    'r cochlea OPT',
    'R cochlea opt',
    'r cochlea opt',
    'r cochlea PRV',
    'R cochlea PRV',
    'R cochlea ps',
    'R cochlea PS',
    'r cochlea ps',
    'r cochlea PS',
    'R cochlea2',
    'R CochleaPRV',
    'r cochlear',
    'R Cochlear',
    'R cochlear',
    'R cochlear Opt',
    'R cochlear opt',
    'r cochlear OPT',
    'R cochlear OPT',
    'R cochlear PS',
    'R cochlear ps',
    'R Cochlear SLD',
    'r cocleaa',
    'Rcochlea',
    'Rcochlea OPT',
    'right  cochlea',
    'right cochlea',
    'Right cochlea',
    'right cochlea OPT',
    'Right cochlea OPT',
    'right cochlea PS',
    'rt cochlea',
    'Rt Cochlea',
    'RT COCHLEA OPT',
    'Rt Cochlea Opt',
    'Rt Cochlea PRV',
    'rt cochlea PRV',
    'Rt OPT Cochlea']
head_and_neck_plan['eye_left'] = [
    'Eye Left',
    'Eye Left PRV',
    'Eye Left PS',
    'Eye Lt',
    'EYE_L',
    'EYE_L OPT',
    'L  eye',
    'l eye',
    'L eye',
    'l eye PRV',
    'LEFT EYE',
    'Left eye',
    'Left Eye',
    'left eye',
    'left eye PRV',
    'Lt Eye',
    'Lt eye',
    'lt eye',
    'Lt eye PRV',
    'OPT Lt eye',
    'PRV L eye',
    'PRV l eye',
    'PRV LtEye']
head_and_neck_plan['eye_right'] = [
    'Eye Right',
    'Eye Right PRV',
    'Eye Right PS',
    'Eye Rt',
    'EYE_R',
    'EYE_R OPT',
    'OPT Rt eye',
    'PRV R eye',
    'PRV r eye',
    'PRV RtEye',
    'r eye',
    'R eye',
    'r eye PRV',
    'RIGHT EYE',
    'Right eye',
    'right eye',
    'right eye PRV',
    'Rt Eye',
    'Rt eye',
    'rt eye',
    'Rt eye_PRV']
head_and_neck_plan['globe_left'] = [
    'globe L',
    'Globe L',
    'globe L PRV',
    'Globe left',
    'Globe Lt',
    'Globe Lt PRV',
    'GLOBE_L',
    'GLOBE_L_SP',
    'l  globe',
    'l Globe',
    'L Globe',
    'L GLobe',
    'l globe',
    'L globe',
    'L Globe Opt',
    'L Globe OPT',
    'L Globe prv',
    'L Globe PRV',
    'L globe prv',
    'l globe PRV',
    'L globe PS',
    'L globe ps',
    'L Globe PS',
    'l globe PS',
    'L globeOPT',
    'Left globe',
    'left globe',
    'Left Globe',
    'Left globe PRV',
    'Left globe PS',
    'left globe PS',
    'Left globePRV',
    'Lt Globe',
    'LT GLOBE',
    'Lt Globe Opt',
    'Lt Globe PRV',
    'OPT Lt Globe',
    'prv l globe',
    'PRV L Globe',
    'PRV L globe',
    'PRV L GLOBE',
    'PRV LGlobe',
    'prv lt globe',
    'PRV Lt Globe',
    'PRV LtGlobe']
head_and_neck_plan['globe_right'] = [
    'globe R',
    'Globe R',
    'globe R PRV',
    'Globe right',
    'Globe Rt',
    'Globe Rt PRV',
    'GLOBE_R',
    'GLOBE_R_SP',
    'OPT Rt Globe',
    'PRV R GLOBE',
    'PRV R Globe',
    'PRV RGlobe',
    'prv rt globe',
    'PRV Rt Globe',
    'PRV RtGlobe',
    'r globe',
    'R globe',
    'R Globe',
    'R Globe Opt',
    'R Globe OPT',
    'R globe prv',
    'r globe PRV',
    'R Globe prv',
    'R Globe PRV',
    'r globe PS',
    'R Globe PS',
    'R globe ps',
    'R globe PS',
    'R globeOPT',
    'right globe',
    'Right globe',
    'Right Globe',
    'Right globe PRV',
    'right globe PS',
    'Right globe PS',
    'Right globePRV',
    'Right GlobePRV',
    'RT GLOBE',
    'Rt Globe',
    'Rt Globe Opt',
    'Rt Globe PRV']
head_and_neck_plan['lens_left'] = [
    'L  lens',
    'L  lensOPT',
    'L lens',
    'l lens',
    'L Lens',
    'L Lens Opt',
    'L Lens OPT',
    'L Lens opt',
    'l lens PRV',
    'L lens prv',
    'L lens PRV',
    'L lens PS',
    'L Lens PS',
    'L LensPRV',
    'left lens',
    'Left lens',
    'Left lens PRV',
    'left lens PS',
    'Left lens PS',
    'Lens',
    'Lens L',
    'LENS LEFT',
    'lens Left',
    'Lens left',
    'Lens Left',
    'lens left',
    'Lens Left OPT',
    'LENS LEFT OPT',
    'Lens Left PS',
    'lens lt',
    'Lens Lt',
    'Lens Lt prv',
    'Lens Lt TLD',
    'LENS_L',
    'LENS_L opt',
    'LENS_L_',
    'LENS_L_SP',
    'LENS_L_SP OPT',
    'Lense Lt',
    'Lenses PRV',
    'Llens',
    'LLens PRV',
    'LlensOPT',
    'Lt lens',
    'Lt Lens',
    'LT LENS KK',
    'Lt Lens Opt',
    'Lt Lens PRV',
    'Lt Lens PS est',
    'Lt lensPRV',
    'OPT L lens',
    'OPT Lt Lens',
    'PRV l lens',
    'PRV L lens',
    'PRV L Lens',
    'PRV L LENS',
    'PRV Llens',
    'PRV LT LENS',
    'PRV Lt Lens',
    'PRV LT LENS KK',
    'PRV LtLens']
head_and_neck_plan['lens_right'] = [
    'Lens R',
    'lens right',
    'Lens Right',
    'lens Right',
    'Lens right',
    'LENS RIGHT',
    'lens right OPT',
    'LENS RIGHT OPT',
    'Lens Right PS',
    'Lens Rt',
    'lens rt',
    'Lens Rt prv',
    'Lens Rt TLD',
    'LENS_R',
    'LENS_R opt',
    'LENS_R_SP',
    'LENS_R_SP OPT',
    'Lense Rt',
    'OPT R lens',
    'OPT Rt Lens',
    'PRV R lens',
    'PRV R Lens',
    'PRV R LENS',
    'PRV r lens',
    'PRV Rlens',
    'PRV RT LENS',
    'PRV Rt Lens',
    'PRV RT LENS KK',
    'PRV RtLens',
    'r lens',
    'R Lens',
    'R lens',
    'R Lens opt',
    'R Lens Opt',
    'R Lens OPT',
    'R Lens PRV',
    'r lens PRV',
    'R lens PRV',
    'R lens prv',
    'R Lens PS',
    'R lens PS',
    'R Lens_1',
    'R Lense OPT',
    'R lensOPT',
    'R LensPRV',
    'Right  lens',
    'right  lens',
    'Right  lens PRV',
    'right lens',
    'Right lens',
    'Right Lens',
    'Right lens PRV',
    'Right lens PS',
    'right lens PS',
    'Rlens',
    'RlensOPT',
    'rt lens',
    'Rt Lens',
    'Rt lens',
    'RT LENS KK',
    'Rt Lens Opt',
    'Rt Lens PRV',
    'rt lens PS est',
    'Rt lensPRV']
head_and_neck_plan['mandible'] = [
    'Mandible',
    'MANDIBLE',
    'mandible',
    'mandible edit',
    'Mandible planner',
    'Mandible_NE',
    'MANDIBLE_SP',
    'right mandible']
head_and_neck_plan['optic_chiasm'] = [
    'CHIASM',
    'chiasm',
    'Chiasm',
    'Chiasm PRV',
    'chiasm PRV',
    'chiasm prv',
    'CHIASM PRV',
    'ChiasmPRV',
    'chiasmPRV',
    'op chiasm',
    'opt chiasm',
    'optic chiasm',
    'optic Chiasm',
    'Optic Chiasm',
    'Optic chiasm',
    'optic Chiasm PRV',
    'Optic chiasm PRV',
    'optic chiasm prv',
    'Optic chiasm prv',
    'optic chiasm PRV',
    'optic chiasmPRV',
    'Optic ChiasmPRV',
    'PRV Chiasm',
    'PRV CHIASM',
    'PRV chiasm',
    'PRV Optic Chiasm',
    'PRV optic chiasm',
    'PRV OPTIC CHIASM']
head_and_neck_plan['optic_nerve_left'] = [
    'L o nerve',
    'l op nerve',
    'L optic nerve',
    'L Optic Nerve',
    'L Optic nerve',
    'l optic nerve',
    'l optic nerve prv',
    'l optic nerve PRV',
    'L Optic nerve PRV',
    'L Optic Nerve PRV',
    'L optic nerve PRV',
    'L optic nerve prv',
    'L optic nervePRV',
    'L otpic nerve',
    'L otpic nerve PRV',
    'Left optic nerve',
    'left optic nerve',
    'left optic nerve PRV',
    'Left optic nerve PRV',
    'lt opitc nerve',
    'Lt Optic Nerve',
    'Lt optic nerve',
    'Lt Optic Nerve PRV',
    'Lt Optic nerve PRV',
    'LT OPTIC NERVE PRV',
    'Lt optic nerve PRV',
    'Lt optic nervePRV',
    'OPTIC NERVE LEFT',
    'Optic nerve Lt',
    'Optic nerve Lt PRV',
    'PRV L op nerve',
    'PRV L Optic nerve',
    'PRV L Optic Nerve',
    'PRV L optic nerve',
    'PRV left optic nerve',
    'PRV Lt Optic Nerve',
    'PRV LtOpticNerve',
    'PRVLeft optic nerve']
head_and_neck_plan['optic_nerve_right'] = [
    'OPTIC NERVE RIGHT',
    'Optic nerve Rt',
    'Optic nerve Rt prv',
    'PRV R optic nerve',
    'PRV R Optic nerve',
    'PRV R Optic Nerve',
    'PRV right optic nerve',
    'PRV Rt op nerve',
    'PRV Rt Optic Nerve',
    'PRV RtOpticNerve',
    'PRVRight optic nerve',
    'R o nerve',
    'r op nerve',
    'R Optic Nerve',
    'R Optic nerve',
    'R optic nerve',
    'r optic nerve',
    'R optic nerve PRV',
    'R Optic Nerve PRV',
    'r optic nerve PRV',
    'r optic nerve prv',
    'R optic nerve prv',
    'R optic nervePRV',
    'R otpic nerve',
    'R otpic nerve PRV',
    'right optic nerve',
    'Right optic nerve',
    'right optic nerve PRV',
    'Right optic nerve PRV',
    'Rt Optic Nerve',
    'Rt optic nerve',
    'rt optic nerve',
    'Rt optic nerve PRV',
    'RT OPTIC NERVE PRV',
    'Rt Optic nerve PRV',
    'Rt Optic Nerve PRV',
    'Rt optic nervePRV']
head_and_neck_plan['parotid_left'] = [
    'L  parotid',
    'L parotid',
    'L Parotid',
    'l parotid',
    'L parotid b',
    'L Parotid opt',
    'left  parotid',
    'left parotid',
    'Left Parotid',
    'Left PAROTID',
    'Left parotid',
    'left parotid PRV',
    'LeftParotid',
    'Lt parotid',
    'lt parotid',
    'LT parotid',
    'Lt Parotid',
    'Lt PAROTID',
    'Parotid L',
    'parotid L',
    'Parotid left',
    'parotid left',
    'Parotid Lt',
    'PAROTID_L',
    'PAROTID_L1',
    'PAROTID_L_SP']
head_and_neck_plan['parotid_right'] = [
    'Parotid R',
    'parotid R',
    'parotid right',
    'PAROTID RIGHT',
    'Parotid right',
    'Parotid Rt',
    'PAROTID_R',
    'PAROTID_R1',
    'PAROTID_R_',
    'PAROTID_R_SP',
    'PRV RT parotid',
    'R  parotid',
    'R Parotid',
    'r parotid',
    'R parotid',
    'R parotid b',
    'right parotid',
    'Right PAROTID',
    'Right Parotid',
    'Right parotid',
    'right parotid PRV',
    'RightParotid',
    'Rt Parotid',
    'rt parotid',
    'Rt parotid',
    'RT PAROTID']
head_and_neck_plan['pituitary_gland'] = [
    'Pituatary',
    'pituiatry',
    'Pituitary',
    'pituitary',
    'Pituitary b',
    'Pituitary Opt',
    'Pituitary OPT',
    'pituitary PRV',
    'Pituitary PRV',
    'pituitary ps',
    'pituitaryPRV',
    'piuitary',
    'PRV Pituitary',
    'PRV pituitary']
head_and_neck_plan['smg_left'] = [
    'L  submandibular',
    'l sm gland',
    'L SMG',
    'L smg',
    'l smgland',
    'L submadibular',
    'l submadibular',
    'l submand',
    'L submandib',
    'l submandib',
    'L submandibular',
    'l submandibular',
    'L SUBMANDIBULAR',
    'L Submandibular',
    'L submandibular gland',
    'l submandibular gland',
    'L submandibular opt',
    'left SMG',
    'left subm gland',
    'left submamandibular glan',
    'left submand  gland',
    'left submand gl',
    'left submand gland',
    'Left submandibular',
    'left submandibular',
    'Left Submandibular',
    'Left submandibular AJ',
    'left submandibular g',
    'left submandibular gl',
    'left submandibular gland',
    'Left submandibular gland',
    'Lt SMG',
    'Lt submand',
    'lt submand',
    'lt submand gland',
    'Lt Submandib',
    'Lt Submandibular',
    'lt submandibular',
    'Lt submandibular galnd',
    'Lt Submandibular Gland',
    'lt SubmanG',
    'Subman Lt',
    'Submand left',
    'Submandibular gland Lt',
    'SUBMANDIBULAR L',
    'Submandibular L',
    'submandibular left',
    'Submandibular Lt',
    'SUBMND_SALV_L1']
head_and_neck_plan['smg_right'] = [
    'r sm gland',
    'R SMG',
    'R smg',
    'R submadibular',
    'r submand',
    'r submand gland',
    'r submandib',
    'R submandib',
    'R SUBMANDIBULAR',
    'r submandibular',
    'R Submandibular',
    'R submandibular',
    'R submandibular galnd',
    'R submandibular gland',
    'r submandibular gland',
    'R submandidular',
    'right sm gland',
    'Right SMG',
    'right SMG',
    'right submand  gland',
    'right submand gl',
    'Right submandibular',
    'RIght submandibular',
    'Right submandibular AJ',
    'right submandibular g',
    'right submandibular gl',
    'right submandibular gland',
    'Right submndblr gland',
    'Rt SM Gland',
    'Rt SMG',
    'rt submand',
    'rt submand gland',
    'RT SUBMANDBLR',
    'Rt Submandib',
    'rt submandibular',
    'Rt Submandibular',
    'Rt submandibular gland',
    'Rt Submandibular Gland',
    'Rt SubmanG',
    'Subman Rt',
    'Submand right',
    'Submandibular gland Rt',
    'Submandibular R',
    'submandibular right',
    'Submandibular Rt',
    'SUBMND_SALV_R1']
head_and_neck_plan['spc'] = [
    'OPT PHARYN_CONST',
    'PHARYN_CONST',
    'PHARYN_CONST_OPT',
    'PHARYN_CONST_SP']
head_and_neck_plan['spinal_cord'] = [
    'cord',
    'Cord',
    'Cord b',
    'cord PRV',
    'Cord PRV',
    'cord prv',
    'cordPRV',
    'CordPRV',
    'PRV CORD',
    'PRV cord',
    'PRV Cord',
    'prv cord',
    'PRV Spinal Canal',
    'PRV Spinal Cord',
    'PRV SPINAL CORD',
    'PRV spinal cord',
    'PRV Spinal cord',
    'PRV SPINAL_CANAL',
    'PRV SPINAL_CORD',
    'PRVCord',
    'PRVspinal cord',
    'PRVSpinalCord',
    'SPINAL CANAL PRV',
    'Spinal Canal PRV',
    'Spinal Cord',
    'spinal cord',
    'Spinal cord',
    'SPINAL CORD',
    'Spinal cord PRV',
    'SPINAL CORD PRV',
    'Spinal Cord PRV',
    'spinal cord PRV',
    'spinal cord prv',
    'spinal cord sjj',
    'Spinal cord SLD',
    'Spinal cordPRV',
    'spinal cordPRV',
    'Spinal CordPRV',
    'SPINAL_CANAL',
    'SPINAL_CANAL PRV',
    'SPINAL_CANAL_OPT',
    'SPINAL_CANAL_PRV',
    'SPINAL_CANAL_SP',
    'SPINAL_CANAL_SP PR',
    'SPINAL_CANAL_SP PRV',
    'SPINAL_cord',
    'SPINAL_CORD',
    'SPINAL_CORD_',
    'SPINAL_cord_SP',
    'SPINAL_CORDprv',
    'SpinalCord',
    'SpinalCord PRV',
    'Spine cord']

head_and_neck_voxtox = {}
head_and_neck_voxtox['alterio_pc'] = [
    "Alertio PC's",
    "Alterio PC's",
    'Alterio PCs',
    'Alterior PCs']
head_and_neck_voxtox['mpc'] = ['MPC', 'MPCs']
head_and_neck_voxtox['oral_cavity'] = [
    'Oral cavity', 'oral cavity']
head_and_neck_voxtox['parotid_left'] = [
    'left parotid',
    'left Parotid',
    'Left parotid',
    'Left Parotid']
head_and_neck_voxtox['parotid_right'] = [
    'right parotid', 'Right parotid', 'Right Parotid']
head_and_neck_voxtox['sg_larynx'] = [
    'Groningen OARs', 'SG larynx']
head_and_neck_voxtox['smg_left'] = [
    'Left SMG',
    'left SMG',
    "left SMG's",
    'Left submandibular']
head_and_neck_voxtox['smg_right'] = [
    'right SMG', 'Right SMG', "right SMG's"]
head_and_neck_voxtox['spc'] = ['SPC', 'SPCs']
head_and_neck_voxtox['spinal_cord'] = [
    'Cord',
    'Spinal cord',
    'spinal cord',
    'spinal cord - DN']

head_and_neck_iov = {}
head_and_neck_iov['parotid_left_1'] = [
    'left parotid']
head_and_neck_iov['parotid_left_2'] = [
    'left parotid 2', 'left parotid 2 for IOV']
head_and_neck_iov['parotid_right_1'] = [
    'right parotid']
head_and_neck_iov['parotid_right_2'] = [
    'right parotid 2', 'right parotid 2 for IOV']
head_and_neck_iov['smg_left_1'] = ['left SMG']
head_and_neck_iov['smg_left_2'] = [
    'left SMG 2', 'Left SMG 2']
head_and_neck_iov['smg_right_1'] = ['right SMG']
head_and_neck_iov['smg_right_2'] = ['Right SMG 2']
head_and_neck_iov['spc_1'] = [
    'pharyngeal consrtictor',
    'pharyngeal constrictor',
    'pharyngeal constrictors']
head_and_neck_iov['spc_2'] = ['SPC 2']
head_and_neck_iov['spinal_cord_1'] = [
    'spinal cord']
head_and_neck_iov['spinal_cord_2'] = [
    'cord2 for IOV']

head_and_neck_mvct = {}
head_and_neck_mvct['parotid_left'] = [
    'left parotid', 'Left parotid']
head_and_neck_mvct['parotid_right'] = [
    'right parotid', 'Right parotid']
head_and_neck_mvct['smg_left'] = ['left SMG']
head_and_neck_mvct['smg_right'] = ['right SMG']
head_and_neck_mvct['spc'] = [
    'pharngeal constrictors',
    'pharyngeal consrictors',
    'pharyngeal constrictor',
    'pharyngeal constrictors']
head_and_neck_mvct['spinal_cord'] = [
    'spinal cord']

head_and_neck_parotid_fiducials = {}
head_and_neck_parotid_fiducials['anterior_left'] = [
    'Ant (L)']
head_and_neck_parotid_fiducials['anterior_right'] = [
    'Ant (R)']
head_and_neck_parotid_fiducials['lateral_left'] = [
    'Lateral (L)', 'lateral (L)']
head_and_neck_parotid_fiducials['lateral_right'] = [
    'Lateral (R)']
head_and_neck_parotid_fiducials['mandible_left'] = [
    'Mandible (L)', 'mandible (L)']
head_and_neck_parotid_fiducials['mandible_right'] = [
    'mandible (R)', 'Mandible (R)']
head_and_neck_parotid_fiducials['mastoid_left'] = [
    'Mastoid (L)']
head_and_neck_parotid_fiducials['mastoid_right'] = [
    'Mastoid (R)']
head_and_neck_parotid_fiducials['medial_left'] = [
    'Medial (L)', 'medial (L)']
head_and_neck_parotid_fiducials['medial_right'] = [
    'Medial (R)', 'medial (R)']
head_and_neck_parotid_fiducials['parotid_left'] = [
    'left parotid']
head_and_neck_parotid_fiducials['parotid_right'] = [
    'right parotid']
head_and_neck_parotid_fiducials['posterior_left'] = [
    'Post (L)']
head_and_neck_parotid_fiducials['posterior_right'] = [
    'Post (R)']

head_and_neck_tre = {}
head_and_neck_tre['c2_c3'] = ['C2/3']
head_and_neck_tre['parotid_anterior_left'] = [
    'left parotid ant']
head_and_neck_tre['parotid_anterior_right'] = [
    'right parotid ant']
head_and_neck_tre['parotid_mastoid_left'] = [
    'left parotid mastoid']
head_and_neck_tre['parotid_mastoid_right'] = [
    'right parotid mastoid']
head_and_neck_tre['pterygoid_plate_left'] = [
    'left pterygoid plate']
head_and_neck_tre['pterygoid_plate_right'] = [
    'right pterygoid plate']
