'''Dictionaries for standardising ROI labels of prostate cohort.'''

prostate_plan = {}
prostate_plan['air'] = [
    'air',
    'Air',
    'air in PTV60',
    'air in PTV74',
    'air in rectum',
    'Air in rectum',
    'Air in Rectum',
    'Air Override']
prostate_plan['bladder'] = [
    'Bladdder',
    'BLADDER',
    'Bladder',
    'bladder',
    'BLADDER (edited by KY)',
    'bladderkw',
    'OAR_bladder']
prostate_plan['femoral_head_left'] = [
    'Femoral head left',
    'femoral head_lt',
    'FEMORAL_HEAD_L',
    'Femur left',
    'Femur Left',
    'Femur Left PRV',
    'FEMUR_HEAD_L',
    'hip l',
    'l fem head',
    'L fem head',
    'L Femoral Head',
    'L FEMORAL HEAD',
    'l femoral head',
    'L femoral head',
    'L femur head',
    'l hip',
    'L HIP',
    'L hip',
    'L Hip',
    'L Hip (THR)',
    'L Hip PRV',
    'left femoral head',
    'Left femoral head',
    'Left hip',
    'left hip',
    'Left Hip',
    'left hip PRV',
    'Lhip',
    'lt fem head',
    'LT fem head',
    'Lt femoral head',
    'Lt Femoral Head',
    'Lt femoral Head',
    'Lt Hip',
    'Lt hip',
    'lt hip',
    'LT HIP',
    'LT hip',
    'lT HIP',
    'Lt Hip PRV',
    'Lt hip PRV',
    'OAR_left hip',
    'PRV Lt Hip']
prostate_plan['femoral_head_right'] = [
    'femoral head_rt',
    'FEMORAL_HEAD_R',
    'Femur Right',
    'FEMUR_HEAD_R',
    'hip r',
    'L femur',
    'left femur',
    'left head of femur',
    'Lt Femur',
    'OAR_right hip',
    'PRV Rt Hip',
    'r  hip',
    'R fem head',
    'R Fem head',
    'r fem head',
    'r femoral head',
    'R Femoral Head',
    'R femoral head',
    'R FEMORAL HEAD',
    'R femur',
    'R femur head',
    'R head fem',
    'r hip',
    'R HIP',
    'R hip',
    'R Hip',
    'Rfemur',
    'rhip',
    'Right femoral head',
    'right femoral head',
    'right femur',
    'right head of femur',
    'Right Hip',
    'right hip',
    'right hip PRV',
    'rt fem head',
    'Rt fem head',
    'RT fem head',
    'rt femoral head',
    'Rt femoral Head',
    'Rt femoral head',
    'Rt Femoral Head',
    'Rt femur',
    'Rt hip',
    'Rt Hip',
    'rt hip',
    'RT hip',
    'RT Hip',
    'RT HIP',
    'rT HIP',
    'Rt Hip PRV',
    'Rt hip_',
    'Rthip']
prostate_plan['pelvic_floor_muscles'] = [
    'Pelvic floor muscles']
prostate_plan['prostate'] = [
    'ctv prostate',
    'CTV prostate',
    'CTV_prostate',
    'pr',
    'Pr',
    'Pro',
    'Pros',
    'PROS',
    'pros',
    'Prosate',
    'Prosta',
    'Prostate',
    'prostate',
    'PROSTATE',
    'Prostate (CTV2)',
    'prostate (KY)',
    'Prostate 1',
    'prostate ctv',
    'Prostate CTV',
    'prostate CTV',
    'prostate only',
    'Prostate Only',
    'Prostate only',
    'Prostate_1']
prostate_plan['prostate_and_seminal_vesicles'] = [
    'JEN PROS + SV',
    'Pr+sv',
    'pr+sv',
    'Pros &SV',
    'Pros + SVs',
    'Pros sv',
    'Pros&SVs',
    'Pros+base sv',
    'pros+sv',
    'Pros+sv',
    'PROS+sv',
    'PROS+SV',
    'Pros+sv_1',
    'Pros+svSGR',
    'Prosate and SVs',
    'ProsSVs',
    'Prosta+sv',
    'Prostate  SVs',
    'Prostate & SV',
    'prostate & SV',
    'prostate & SV (KY)',
    'prostate &SV',
    'Prostate &SV',
    'Prostate + base sv',
    'Prostate + Rsv',
    'Prostate + seminal vesicles',
    'Prostate + sv',
    'prostate + SV',
    'Prostate + SV',
    'Prostate + SV (CTV1)',
    'Prostate + SVs',
    'prostate + SVs',
    'Prostate +SV',
    'Prostate 1 + SV',
    'prostate and SV',
    'Prostate and sv',
    'prostate and sv',
    'prostate and SVs',
    'Prostate and SVs',
    'prostate sv',
    'Prostate sv',
    'Prostate SVs',
    'Prostate&SV',
    'prostate&sv',
    'Prostate&sv',
    'Prostate&SVs',
    'Prostate+ sv',
    'Prostate+base sv',
    'Prostate+basesv',
    'prostate+sv',
    'PROSTATE+sv',
    'PROSTATE+SV',
    'Prostate+sv',
    'Prostate+SV',
    'Prostate+SVs',
    'Prostate+svs',
    'Prostate+SVs (CTV1)',
    'prostate/sv',
    'Prostate/sv',
    'Prostate/SV',
    'prostate/SV',
    'Prostate/SVs',
    'Prostatesv',
    'proxSeminal vesicles CTV',
    'PTV_SV + PTV_prost',
    'SV + Prostate']
prostate_plan['prostate_bed'] = [
    'prostate bed',
    'Prostate bed',
    'prostate bed2']
prostate_plan['prosthetic_hip_left'] = [
    'left hip prosthesis',
    'Left Prosthesis',
    'LHip Prosthesis',
    'LHip ProsthesisPRV',
    'Lt Pros',
    'Lt prosthesis',
    'Lt prosthesis',
    'Lt Prosthesis',
    'Lt Prosthesis',
    'Lt Prosthesis PRV',
    'Lt Prosthesis PRV',
    'Lt prosthesis PRV',
    'Lt prosthesis PRV',
    'Lt prosthetic',
    'Lt prosthetic',
    'Lt Prosthetic Hip',
    'Lt Prosthetic Hip',
    'Lt prosthsis',
    'Lt prosthsis',
    'PRV Lt Prosthesis',
    'PRV Lt Prosthesis',
    'PRVLt Pros']
prostate_plan['prosthetic_hip_right'] = [
    'Art hip',
    'Art Hip',
    'Art Hip PRV',
    'L Art Hip',
    'L Art Hip PRV',
    'Lt artificial hip',
    'PRV Lt artificial hip',
    'PRV rt artificial hip',
    'PRV Rt Prosthesis',
    'PRV Rt Prosthesis',
    'PRVRt pros',
    'R Art Hip',
    'R Art Hip PRV',
    'right hip prosthesis',
    'Right Prosthesis',
    'Rt Art hip',
    'Rt Art Hip',
    'Rt Art Hip PRV',
    'Rt Art HipPRV',
    'rt artificial hip',
    'Rt pros',
    'Rt Prosthesis',
    'Rt Prosthesis',
    'Rt prosthesis',
    'Rt prosthesis',
    'Rt prosthesis PRV',
    'Rt prosthesis PRV',
    'Rt prosthetic hip',
    'Rt prosthetic hip',
    'Rt prosthetic hip2',
    'Rt prosthetic hip2']
prostate_plan['rectum'] = [
    'OAR_rectum',
    'rectum',
    'Rectum',
    'RECTUM',
    'RECTUM (edited by KY)',
    'RECTUM1',
    'RECTUM2']
prostate_plan['seminal_vesicles'] = [
    'ctv seminal vesicles',
    'ctv sv',
    'CTV SV',
    'CTV_SV',
    'DN CTV_SV',
    'seminal vesicle ctv',
    'seminal vesicle CTV',
    'Seminal vesicles',
    'seminal vesicles',
    'seminal vesicles CTV',
    'sv',
    'Sv',
    'SV',
    'SV CTV',
    'sv ctv',
    'SV ctv',
    "SV's",
    'SVs',
    'Svs']
prostate_plan['sigmoid_colon'] = [
    'Sigmoid', 'Sigmoid colon', 'Sigmoid Colon']

prostate_voxtox = {}
prostate_voxtox['pelvic_floor_muscles'] = [
    'Pelvic floor muscles']
prostate_voxtox['rectum'] = ['Rectum', 'rectum']

prostate_iov = {}
prostate_iov['rectum_am'] = ['Rectum A*M*']
prostate_iov['rectum_cw'] = ['Rectum C*W*']
prostate_iov['rectum_gb'] = ['Rectum G*B*']
prostate_iov['rectum_gh'] = ['Rectum G*H*']
prostate_iov['rectum_jes'] = ['Rectum']
prostate_iov['rectum_lhd'] = ['Rectum L*H*D*']
prostate_iov['rectum_nb'] = ['Rectum N*B*']
prostate_iov['rectum_rb'] = ['Rectum R*B*']
prostate_iov['rectum_sr'] = ['Rectum S*R*']
prostate_iov['rectum_yr'] = ['Rectum Y*R*']
