'''List of names labelling rois outlined by DJN on planning scans.'''
head_and_neck = 253

head_and_neck_voxtox = \
    ["Alertio PC's",
     "Alterio PC's",
     'Alterio PCs',
     'Alterior PCs',
     'Cord',
     'Groningen OARs',
     'Left Parotid',
     'Left SMG',
     'Left parotid',
     'Left submandibular',
     'MPC',
     'MPCs',
     'Oral cavity',
     'PRV SPINAL CORD',
     'Right Parotid',
     'Right SMG',
     'Right parotid',
     'SG larynx',
     'SPC',
     'SPCs',
     'Spinal cord',
     'cord prv',
     'left Parotid',
     'left SMG',
     "left SMG's",
     'left parotid',
     'oral cavity',
     'right SMG',
     "right SMG's",
     'right parotid',
     'spinal cord',
     'spinal cord - DN']
