'''Lists of names labelling rois outlined in clinical planning.'''

# Head-and-neck cohort
head_and_neck_plan = \
    ["'relevant' Chiasm",
     "'relevant' Chiasm PRV",
     '0.5CM BOLUS',
     '10mm',
     '1mm',
     '1mmAll',
     '2MM',
     '2mm',
     '2mm + 61mm',
     '3mm',
     '3mm + 61mm',
     '40Gy avoid',
     '4mm + 61mm',
     '54 + 1',
     '54 L Neck ring',
     '54 Shell Inner',
     '54 outer ring',
     '54 ring',
     '54 shell',
     '54-L Ring',
     '54-L outer ring',
     '54-R Outer ring',
     '54-R Ring',
     '54R neck ring',
     '5MM',
     '5mm ring',
     '60 + 1',
     '60 Ring',
     '60 Shell',
     '60 Shell Inner',
     '60 inner ring',
     '60 outer Ring',
     '60 ring',
     '60 ring outer',
     '60PTV ring',
     '61mm',
     '65 + 1',
     '65 AVOID',
     '65 Avoid',
     '65 Ring',
     '65 ring',
     '65 shell',
     '65PTV ring',
     'AIR',
     'ALLPTV',
     'ANT AVOID',
     'ARTEFACTS',
     'ARTIFACT',
     'ARTIFACTS',
     'AVIOD LARGE',
     'AVIOD SMALL',
     'AVOID',
     'AVOID Jaw Hotspots',
     'Air',
     'Air and PTV60p',
     'Air in PTV',
     'Air in PTV60',
     'All PTV',
     'All PTV 60',
     'All PTVs',
     'Ant AVOID',
     'Ant Avoid',
     'Ant avoid',
     'Ant block',
     'Artefact',
     'Artefact Density 1',
     'Artefact density 1',
     'Artefact-dens override',
     'Artefacts',
     'Artefcat',
     'Artefcts',
     'Arterfacts',
     'Artifact',
     'Artifacts',
     'Avoid',
     'Avoid BS',
     'Avoid remaining',
     'B Stem',
     'B StemPRV',
     'B stem',
     'B stem PRV',
     'B stemPRV',
     'BLOCK',
     'BLOCK CORD',
     'BLOCK OPTICS',
     'BRAIN',
     'BRAIN AVOID',
     'BRAIN2',
     'BRAINSTEM',
     'BRAINSTEM PRV',
     'BRAINSTEM_',
     'BRAINSTEM_PRV',
     'BRAINSTEM_SP',
     'BRAINSTEM_SP PRV',
     'BRAINSTEM_old',
     'BRAIN_SP',
     'BS PS',
     'BUFFER',
     'Big Ring',
     'Body',
     'Body inner',
     'Body-3mm',
     'Bolus',
     'Bolus real',
     'Boost CTV6',
     'Brain',
     'Brain Stem',
     'Brain Stem PRV',
     'Brain stem',
     'Brain stem PRV',
     'Brain stem prv',
     'Brain stemPRV',
     'Brain stemprv',
     'BrainStem PRV',
     'Brainstem',
     'Brainstem AVOID',
     'Brainstem AVoid1mm',
     'Brainstem PRV',
     'Brainstem b',
     'Brainstem prv',
     'BrainstemPRV',
     'Brrainstem PRV',
     'Brsinstem',
     'Buffer',
     'Buffer65',
     'CE - do not plan',
     'CE vol - do not plan',
     'CE-teaching - do not plan',
     'CHIASM',
     'CHIASM PRV',
     'COCHLEA RIGHT',
     'COCHLEA_L',
     'COCHLEA_L - SLD',
     'COCHLEA_L Avoid',
     'COCHLEA_L OPT',
     'COCHLEA_L PS',
     'COCHLEA_L_OPT',
     'COCHLEA_L_Opt',
     'COCHLEA_L_PS',
     'COCHLEA_L_SP',
     'COCHLEA_L_SP OPT',
     'COCHLEA_L_SP opt',
     'COCHLEA_L_edited',
     'COCHLEA_L_opt',
     'COCHLEA_R',
     'COCHLEA_R - OPT',
     'COCHLEA_R - SLD',
     'COCHLEA_R OPT',
     'COCHLEA_R Opt',
     'COCHLEA_R PS',
     'COCHLEA_R_OPT',
     'COCHLEA_R_PS',
     'COCHLEA_R_SP',
     'COCHLEA_R_SP OPT',
     'COCHLEA_R_SP opt',
     'COCHLEA_R_edited',
     'COCHLEA_R_opt',
     'CORD BLOCK',
     'COUCH',
     'CT Artefact',
     'CTV',
     'CTV  T 60',
     'CTV 54',
     'CTV 54 L neck',
     'CTV 54 Left neck',
     'CTV 54 R neck',
     'CTV 54 neck L',
     'CTV 54 neck R',
     'CTV 54Gy',
     'CTV 54Gy_1',
     'CTV 54L',
     'CTV 54Ra',
     'CTV 54Rb',
     'CTV 60',
     'CTV 60 L',
     'CTV 60 R',
     'CTV 60 R nodes',
     'CTV 60 Right neck',
     'CTV 60 clipped',
     'CTV 60 neck L',
     'CTV 60 orop',
     'CTV 60(original)',
     'CTV 60Gy',
     'CTV 60L',
     'CTV 65',
     'CTV 65 L',
     'CTV 65 L (b)',
     'CTV 65 Node',
     'CTV 65 R',
     'CTV 65 combined',
     'CTV 65 node',
     'CTV 65 primary',
     'CTV 65 tonsil',
     'CTV 68',
     'CTV 68 L',
     'CTV 68 Lt',
     'CTV 68 Rt',
     'CTV 68Gy',
     'CTV 68_1',
     'CTV 70',
     'CTV L 54',
     'CTV L Neck 54 - sjj',
     'CTV N 60',
     'CTV N 60 L',
     'CTV N L neck 65Gy',
     'CTV N R neck 65Gy',
     'CTV N60 L',
     'CTV N65',
     'CTV R 54',
     'CTV R N',
     'CTV R Neck 60 SJJ',
     'CTV Right 60',
     'CTV T 60',
     'CTV T 65',
     'CTV T60',
     'CTV clipped',
     'CTV left 60',
     'CTV node 65',
     'CTV node 70',
     'CTV nodes 54 prophylacti',
     'CTV nodes 60',
     'CTV nodes 60 + CTV prima',
     'CTV nodes 65',
     'CTV nodes 70',
     'CTV nodes L 54',
     'CTV nodes L 60',
     'CTV nodes R 54',
     'CTV p70',
     'CTV primary 65',
     'CTV primary and RP 65 + CTV nodes',
     'CTV t 60',
     'CTV t 65',
     'CTV- LN65',
     'CTV-50',
     'CTV-54',
     'CTV-54L',
     'CTV-54R2',
     'CTV-55',
     'CTV-60',
     'CTV-60R',
     'CTV-65',
     'CTV-65N',
     'CTV-65T',
     'CTV-N',
     'CTV-N 60',
     'CTV-N 65',
     'CTV-N2',
     'CTV-N54',
     'CTV-N54L',
     'CTV-N60',
     'CTV-N65',
     'CTV-N65_1',
     'CTV-P65',
     'CTV-T',
     'CTV-T 60',
     'CTV-T 65',
     'CTV-T60',
     'CTV-T65',
     'CTV1  60Gy',
     'CTV1  60Gy L',
     'CTV1  60Gy L lower',
     'CTV1  68Gy',
     'CTV50',
     'CTV50L',
     'CTV50R',
     'CTV54',
     'CTV54 (level V)',
     'CTV54 L',
     'CTV54 L 2',
     'CTV54 L Neck Nodes',
     'CTV54 L neck',
     'CTV54 L neck_1',
     'CTV54 L1',
     'CTV54 N (level IV)',
     'CTV54 R',
     'CTV54 R Neck nodes',
     'CTV54 R neck',
     'CTV54-L',
     'CTV54-LEFT',
     'CTV54-LNECK',
     'CTV54-R',
     'CTV54-RIGHT-IV',
     'CTV54-RIGHT-V',
     'CTV54-RNECK',
     'CTV54-R_level V',
     'CTV54L',
     'CTV54L - sjj',
     'CTV54L1',
     'CTV54L2',
     'CTV54L_2',
     'CTV54Lb',
     'CTV54N-L',
     'CTV54N-R',
     'CTV54R',
     'CTV54R clipped',
     'CTV54R-3',
     'CTV54R1',
     'CTV54R2',
     'CTV54R_2',
     'CTV54R_3',
     'CTV54_L',
     'CTV54_R',
     'CTV54_level VII',
     'CTV55',
     'CTV60',
     'CTV60 - tonsil',
     'CTV60 L neck',
     'CTV60 R',
     'CTV60 R Neck',
     'CTV60 R neck',
     'CTV60 inf',
     'CTV60 l neck',
     'CTV60 lower Rt',
     'CTV60 sup',
     'CTV60-L',
     'CTV60-LNECK',
     'CTV60-OP',
     'CTV60-P',
     'CTV60-R',
     'CTV60-RIGHT',
     'CTV60-T',
     'CTV60-VII',
     'CTV60L',
     'CTV60L Neck',
     'CTV60R',
     'CTV60Ra',
     'CTV60Rb',
     'CTV60SJJ',
     'CTV60T',
     'CTV60_L',
     'CTV60_L Neck',
     'CTV60_R',
     'CTV60_R Neck',
     'CTV60l',
     'CTV60primary',
     'CTV60r',
     'CTV65',
     'CTV65 (b)',
     'CTV65 - Node',
     'CTV65 - tonsil',
     'CTV65 L neck',
     'CTV65 L-N',
     'CTV65 T',
     'CTV65+10',
     'CTV65-LN',
     'CTV65-N',
     'CTV65-R-N2',
     'CTV65-T',
     'CTV65-p',
     'CTV65Gy',
     'CTV65L',
     'CTV65N',
     'CTV65R',
     'CTV65T',
     'CTV65_1',
     'CTV65_L',
     'CTV65_L2',
     'CTV65_L_N',
     'CTV65_R',
     'CTV65_R_N',
     'CTV65_T',
     'CTV68',
     'CTV68 primary',
     'CTVL54',
     'CTVN 54R',
     'CTVN 65',
     'CTVN54 R',
     'CTVN54L',
     'CTVN54_sjj',
     'CTVN60',
     'CTVN60 R',
     'CTVN60L',
     'CTVN65-R - need bolus',
     'CTVN65_SJJ',
     'CTVNL65',
     'CTVN_54',
     'CTVN_54_AJ',
     'CTVR54',
     'CTVR60',
     'CTVT60',
     'CTV_54',
     'CTV_54L',
     'CTV_55',
     'CTV_60',
     'CTV_65',
     'CTV_65N',
     'CTV_68',
     'CTV_N60 - sjj',
     'CTV_N_54',
     'CTV_N_60',
     'CTV_N_65',
     'CTV_N_L2_65',
     'CTV_N_L_65',
     'CTV_N_R65',
     'CTV_T_60',
     'CTV_T_65',
     'CTVn 70',
     'CTVnodal65',
     'CTVnodes68',
     'CTVp60',
     'CV65',
     'Chiasm',
     'Chiasm PRV',
     'Chiasm in PTV',
     'ChiasmPRV',
     'Cochlea L',
     'Cochlea L OPT',
     'Cochlea Lt',
     'Cochlea Lt + 3mm',
     'Cochlea R',
     'Cochlea R OPT',
     'Cochlea Rt',
     'Cochlea Rt + 3mm',
     'Cochlea left',
     'Cochlea right',
     'Cord',
     'Cord Block',
     'Cord Buffer 2',
     'Cord Buffer 60',
     'Cord PRV',
     'Cord PRV INF',
     'Cord PRV SUP',
     'Cord b',
     'Cord buffer 65',
     'CordPRV',
     'Costar CTV',
     'Couch',
     'DENTAL WORK',
     'DIRECT POST BLOCK',
     'DOSE AVOID',
     'Density 1',
     'Density 1.5',
     'Density overide',
     'Dental Artefacts',
     'EYE_L',
     'EYE_L OPT',
     'EYE_R',
     'EYE_R OPT',
     'Extended CTV',
     'Eye Avoid',
     'Eye Block',
     'Eye Left',
     'Eye Left PRV',
     'Eye Left PS',
     'Eye Lt',
     'Eye Right',
     'Eye Right AVOID',
     'Eye Right PRV',
     'Eye Right PS',
     'Eye Rt',
     'Eye block',
     'FILLING',
     'FILLINGS',
     'FOV Block',
     'FOV avoid',
     'FOV blocking',
     'Filling',
     'Filling avoid',
     'Filling override to 1.0',
     'Fillings',
     'Final CTV 60',
     'Flare',
     'For Bolus',
     'For p/bolus',
     'G1',
     'GLOBE_L',
     'GLOBE_L - SLD',
     'GLOBE_L Avoid',
     'GLOBE_L_SP',
     'GLOBE_R',
     'GLOBE_R - SLD',
     'GLOBE_R Avoid',
     'GLOBE_R_SP',
     'GLOTTIS',
     'GLOTTIS - PTV',
     'GTV',
     'GTV + 10ax/12supinf',
     'GTV + 15',
     'GTV + 15mm',
     'GTV + 15mm - mandible',
     'GTV + 5mm',
     'GTV - CT',
     'GTV - MRI',
     'GTV - final',
     'GTV 65',
     'GTV 65 nodes',
     'GTV 65 tonsil',
     'GTV 70',
     'GTV N',
     'GTV N1',
     'GTV N2',
     'GTV Node',
     'GTV Node + 10mm',
     'GTV Node + 5',
     'GTV Node - DN',
     'GTV T',
     'GTV n 70',
     'GTV node',
     'GTV node b',
     'GTV nodes',
     'GTV pre-op',
     'GTV primary',
     'GTV primary and RP',
     'GTV tonsil',
     'GTV+10mm',
     'GTV- LN65',
     'GTV-LN',
     'GTV-LN2',
     'GTV-N',
     'GTV-N+5',
     'GTV-N1',
     'GTV-N2',
     'GTV-N3',
     'GTV-N4',
     'GTV-N5',
     'GTV-N6',
     'GTV-P65-(MRI)',
     'GTV-RN65',
     'GTV-RN65_1',
     'GTV-T',
     'GTV-T+10',
     'GTV-T2',
     'GTV/tonsil bed',
     'GTV1',
     'GTV2',
     'GTV65',
     'GTV65-LN',
     'GTV65-T',
     'GTV65-sjj',
     'GTV70',
     'GTVN1',
     'GTVN2',
     'GTVN3',
     'GTVN_SJJ',
     'GTV_65 - R N',
     'GTV_AJ',
     'GTV_L_N',
     'GTV_N',
     'GTV_N_L',
     'GTV_N_L2',
     'GTV_N_R',
     'GTV_T',
     'GTV_n65',
     'GTV_pre-op',
     'GTVnodes',
     'GTVp65',
     'GVT T',
     'Globe L',
     'Globe Lt',
     'Globe Lt PRV',
     'Globe R',
     'Globe Rt',
     'Globe Rt PRV',
     'Globe left',
     'Globe right',
     'Globe-L',
     'Globe-R',
     'Glottis',
     'Glottis - PTV',
     'Glottis outside PTVs',
     'High Density',
     'High Density Fillings',
     'High Desity',
     'High Dose Ring',
     'High ring',
     'I3',
     'ICRU',
     'ICRU POINT',
     'ICRU point',
     'ICRU pt',
     'IMPLANT',
     'IN RING PTV54RT POS',
     'INNER 54',
     'INNER 60',
     'INNER 70',
     'INNER L 60',
     'INNER LT',
     'INNER R 60',
     'INNER RING',
     'INNER RING 65 60 LT',
     'INNER RING PTV54',
     'INNER RING PTV54 LT',
     'INNER RING PTV54 RT',
     'INNER RING PTV54LT',
     'INNER RING PTV54RT',
     'INNER RING PTV60',
     'INNER RING PTV60 LT',
     'INNER RING PTV60 RT',
     'INNER RING PTV60LT',
     'INNER RING PTV60P',
     'INNER RING PTV60P - PTV60 LT',
     'INNER RING PTV60RT',
     'INNER RING PTV65',
     'INNER RING PTV65_60',
     'INNER RING RT',
     'INNER RING60',
     'INNER RING65',
     'INNER RT',
     'INNER SHELL',
     'Inf Avoid',
     'Inf L Avoid',
     'Inf R Avoid',
     'Inf avoid',
     'Inner 54',
     'Inner 60',
     'Inner 60 ring',
     'Inner LT ring',
     'Inner RT ring',
     'Inner Ring',
     'Inner Ring 60',
     'Inner Shell',
     'Inner ring',
     'Inner shell',
     'Inner shell 54',
     'Inner shell 60R',
     'Inner shell-54L_2',
     'Inner shell-60L',
     'Inner-54L',
     'Inner-54R',
     'Ipsilateral neck CTV',
     'L  PTV54',
     'L  eye',
     'L  lens',
     'L  lensOPT',
     'L  parotid',
     'L  parotid - PTV',
     'L  subman- PTV',
     'L  submandibular',
     'L Avoid',
     'L CTV50',
     'L CTV54',
     'L CTV60',
     'L CTV68',
     'L Cochlea',
     'L Cochlea + 3mm',
     'L Cochlea AVOID',
     'L Cochlea OPT',
     'L Cochlea Opt',
     'L CochleaPRV',
     'L Cochlear SLD',
     'L GLobe',
     'L Globe',
     'L Globe OPT',
     'L Globe Opt',
     'L Globe Opt - PTV',
     'L Globe Opt in PTV',
     'L Globe PRV',
     'L Globe PS',
     'L Globe prv',
     'L Inf avoid',
     'L Lacrimal',
     'L Lens',
     'L Lens Avoid',
     'L Lens OPT',
     'L Lens Opt',
     'L Lens PS',
     'L Lens opt',
     'L LensPRV',
     'L Neck CTV',
     'L Neck CTV54',
     'L Neck PTV60',
     'L ON',
     'L ON PRV',
     'L ON PRV - PTV',
     'L ON PRV in PTV',
     'L Optic Nerve',
     'L Optic Nerve AVOID',
     'L Optic Nerve PRV',
     'L Optic Nerve PRV - PTV70',
     'L Optic Nerve PRV and PTV70',
     'L Optic nerve',
     'L Optic nerve PRV',
     'L PAROTID -PTV',
     'L PTV 54',
     'L PTV 60',
     'L PTV 68',
     'L PTV n 65',
     'L PTV nodes 60',
     'L PTV60',
     'L Parotid',
     'L Parotid - PTV',
     'L Parotid - PTV60',
     'L Parotid - PTV60+65',
     'L Parotid - PTVs',
     'L Parotid -PTV',
     'L Parotid opt',
     'L Ring 60',
     'L SMG',
     'L SUB gland-LT LN PTV',
     'L SUBMANDIBULAR',
     'L Sub mand',
     'L Submand - PTV',
     'L Submandibular',
     'L Submandibular - PTV',
     'L cochlea',
     'L cochlea Avoid',
     'L cochlea OPT',
     'L cochlea PRV',
     'L cochlea PS',
     'L cochlea opt',
     'L cochlea ps',
     'L cochlea2',
     'L cochlear',
     'L cochlear AVOID',
     'L cochlear Opt',
     'L cochlear PS',
     'L cochlear opt',
     'L cochlear ps',
     'L eye',
     'L eye Avoid',
     'L globe',
     'L globe AVOID',
     'L globe AVOID - PTV 60',
     'L globe AVOID in PTV 60',
     'L globe Avoid',
     'L globe PS',
     'L globe prv',
     'L globe ps',
     'L globeOPT',
     'L lacrimal',
     'L lacrimal Avoid',
     'L lacrimal OPT',
     'L lacrimal galnd',
     'L lacrimal gland',
     'L lens',
     'L lens AVOID',
     'L lens Avoid',
     'L lens Avoid large',
     'L lens PRV',
     'L lens PS',
     'L lens prv',
     'L neck',
     'L neck CTV60 - sjj',
     'L neck II-IV',
     'L neck Ib-V + VIIa',
     'L neck PTV60',
     'L neck nodes',
     'L neck nodes 54 Gy',
     'L nodes',
     'L o nerve',
     'L op N',
     'L opt n PRV and PTV p70',
     'L optic nerve',
     'L optic nerve PRV',
     'L optic nerve prv',
     'L optic nervePRV',
     'L orbit',
     'L otpic nerve',
     'L otpic nerve PRV',
     'L parotid',
     'L parotid + PTV',
     'L parotid - All PTV',
     'L parotid - All PTV 60',
     'L parotid - PTV',
     'L parotid - PTV 54',
     'L parotid - PTV 60',
     'L parotid - PTV L 54',
     'L parotid - PTV-60',
     'L parotid - PTV54',
     'L parotid - PTV54L',
     'L parotid - PTV54_L',
     'L parotid - PTV60',
     'L parotid - PTV60/65',
     'L parotid - PTVN',
     'L parotid - PTVs',
     'L parotid - ptv',
     'L parotid IN  L PTV65',
     'L parotid IN PTV60',
     'L parotid PTV 60',
     'L parotid and PTV',
     'L parotid and PTV L 54',
     'L parotid b',
     'L parotid in PTV65',
     'L parotid_old',
     'L parotid_old - PTV54',
     'L ring 54',
     'L smg',
     'L sub - PTV',
     'L sub - PTVs',
     'L submadibular',
     'L submadibular - PTV',
     'L subman - PTV',
     'L submand IN PTV60',
     'L submand IN PTV65',
     'L submandib',
     'L submandib - PTV',
     'L submandibular',
     'L submandibular - PTV',
     'L submandibular - PTV60',
     'L submandibular -PTV60',
     'L submandibular gland',
     'L submandibular in 54',
     'L submandibular in PTV60',
     'L submandibular opt',
     'L submandibular_old',
     'L temp lobe',
     'L temporal lobe',
     'L tonsil bed',
     'LARGE AVOID',
     'LAvoid',
     'LCTV54',
     'LCTV60',
     'LCTVn65',
     'LEFT EYE',
     'LENS LEFT',
     'LENS LEFT OPT',
     'LENS RIGHT',
     'LENS RIGHT OPT',
     'LENS_L',
     'LENS_L - SLD',
     'LENS_L Avoid',
     'LENS_L opt',
     'LENS_L_',
     'LENS_L_SP',
     'LENS_L_SP OPT',
     'LENS_R',
     'LENS_R - SLD',
     'LENS_R opt',
     'LENS_R_SP',
     'LENS_R_SP OPT',
     'LH  volume - do not plan',
     'LLens PRV',
     'LN L',
     'LN PTV54',
     'LN R',
     'LNeck CTV60',
     'LNecknodesPTV60',
     'LON PRV',
     'LON prv',
     'LPTV12',
     'LPTV15',
     'LPTV54',
     'LPTV60',
     'LPTVn65',
     'LParotid - PTV',
     'LT COCHLEA OPT',
     'LT GLOBE',
     'LT LENS KK',
     'LT LN PTV',
     'LT LN PTV 60',
     'LT LN PTV54',
     'LT LN PTV60',
     'LT LOW PTV 68',
     'LT LOW SHELL 68',
     'LT OPTIC NERVE PRV',
     'LT PTV 60',
     'LT PTV 68',
     'LT PTV60',
     'LT PTV60 ring',
     'LT PTV65',
     'LT SHELL 60',
     'LT SHELL 68',
     'LT SHOULDER BLOCK',
     'LT neck PTV 54',
     'LT parotid',
     'Large avoid',
     'Larynx',
     'Larynx - PTV',
     'Larynx - PTV60',
     'Larynx -PTV',
     'Larynx Avoid',
     'Larynx avoid',
     'Lavoid',
     'Lctv54',
     'Lctvnodes60',
     'Lcvtnodes65',
     'Left Eye',
     'Left Globe',
     'Left Lung',
     'Left PAROTID',
     'Left PAROTID -PTV54',
     'Left Parotid',
     'Left Parotid - PTV',
     'Left Submandibular',
     'Left avoid',
     'Left cochlea',
     'Left cochlea Avoid',
     'Left cochlea OPT',
     'Left eye',
     'Left globe',
     'Left globe PRV',
     'Left globe PS',
     'Left globe PS - PTV',
     'Left globe PS and PTV 60',
     'Left globePRV',
     'Left lens',
     'Left lens PRV',
     'Left lens PS',
     'Left neck',
     'Left neck CTV 54',
     'Left neck CTV 60',
     'Left optic nerve',
     'Left optic nerve PRV',
     'Left parotid',
     'Left parotid - PTV',
     'Left parotid - PTV 54 Left neck',
     'Left parotid - PTV60L',
     'Left submandibular',
     'Left submandibular - PTV',
     'Left submandibular AJ',
     'Left submandibular gland',
     'LeftParotid',
     'Leftnodes-60',
     'Lens',
     'Lens L',
     'Lens Left',
     'Lens Left OPT',
     'Lens Left PS',
     'Lens Lt',
     'Lens Lt TLD',
     'Lens Lt prv',
     'Lens R',
     'Lens Right',
     'Lens Right PS',
     'Lens Rt',
     'Lens Rt TLD',
     'Lens Rt prv',
     'Lens left',
     'Lens right',
     'Lens-L',
     'Lens-R',
     'Lense Lt',
     'Lense Rt',
     'Lenses PRV',
     'Level II',
     'Level III',
     'LevelIb',
     'Lip',
     'Lip - PTV',
     'Llens',
     'LlensOPT',
     'LnodesPTV54',
     'LnodesPTV60',
     'Low dens artefact',
     'Low density override',
     'Low ring',
     'Lparotid - PTV',
     'Lpost avoid',
     'Lsubman - PTV',
     'Lt 54 Ring',
     'Lt 54 ring',
     'Lt 54PTV Ring',
     'Lt Avoid',
     'Lt CTV 54',
     'Lt Cochlea',
     'Lt Cochlea AVOID',
     'Lt Cochlea Opt',
     'Lt Cochlea PRV',
     'Lt Eye',
     'Lt Globe',
     'Lt Globe Opt',
     'Lt Globe PRV',
     'Lt LN65 ring',
     'Lt LN65PTV',
     'Lt Lacrimal Opt',
     'Lt Lens',
     'Lt Lens Opt',
     'Lt Lens PRV',
     'Lt Lens PS est',
     'Lt N54 Shell',
     'Lt Neck CTV 60',
     'Lt Neck CTV 65',
     'Lt Neck PTV 54',
     'Lt Nodes PTV60',
     'Lt ON PRV',
     'Lt OPT Cochlea',
     'Lt Optic Nerve',
     'Lt Optic Nerve PRV',
     'Lt Optic nerve PRV',
     'Lt Orbit Opt',
     'Lt PAROTID',
     'Lt PAROTID - PTV',
     'Lt PTV 60',
     'Lt PTV54',
     'Lt PTV60',
     'Lt PTV60N',
     'Lt Parotid',
     'Lt Parotid - PTV',
     'Lt Parotid - PTV60',
     'Lt Parotid outside PTV',
     'Lt Ring 54',
     'Lt Ring 60',
     'Lt SMG',
     'Lt SMG - PTV',
     'Lt Shoulder',
     'Lt Shoulder Block',
     'Lt Shoulder block',
     'Lt Sub Estimate JX',
     'Lt Sub Gland',
     'Lt Subm - PTV',
     'Lt Submand - PTV',
     'Lt Submandib',
     'Lt Submandib - PTV',
     'Lt Submandibular',
     'Lt Submandibular - PTV',
     'Lt Submandibular Gland',
     'Lt eye',
     'Lt eye PRV',
     'Lt lens',
     'Lt lensPRV',
     'Lt neck 60',
     'Lt optic nerve',
     'Lt optic nerve PRV',
     'Lt optic nervePRV',
     'Lt parotid',
     'Lt parotid in PTV',
     'Lt shoudler block',
     'Lt shoulder Block',
     'Lt shoulder block',
     'Lt shoulder blocks',
     'Lt submand',
     'Lt submandibular galnd',
     'Lt submandibular galnd - PTV54',
     'Lt54 RING',
     'LtBlock',
     'LtCTV60',
     'LtPTV54',
     'Lung Left',
     'Lung Right',
     'MANDIBLE',
     'MANDIBLE - PTV',
     'MANDIBLE - PTV_1',
     'MANDIBLE IN PTV60',
     'MANDIBLE in  RPTV54',
     'MANDIBLE in LPTV54',
     'MANDIBLE in LPTV60',
     'MANDIBLE in PTV54',
     'MANDIBLE in PTV65',
     'MANDIBLE_SP',
     'MANDIBLE_SP + PTV65',
     'MANDIBLE_SP - MANDIBLE',
     'MANDIBLE_SP - PTV',
     'MANDIBLE_SP - PTV54 RT',
     'MANDIBLE_SP - PTV60',
     'MANDIBLE_SP - PTV65',
     'MANDIBLE_SP - PTV65 com',
     'MANDIBLE_SP - PTV65T +',
     'MANDIBLE_SP - PTV65T - PTV65 RT',
     'MANDIBLE_SP and PTV',
     'MANDIBLE_SP and PTV54 RT',
     'MANDIBLE_SP and PTV60',
     'MANDIBLE_SP and PTV65',
     'MANDIBLE_SP and PTV65-T',
     'MANDIBLE_SP and PTV65T +',
     'MID AVOID',
     'MID RING',
     'MID SHELL',
     'MOUTH AVOID',
     'Mandble',
     'Mandible',
     'Mandible IN PTV60',
     'Mandible and PTV',
     'Mandible avoid',
     'Mandible in PTV',
     'Mandible in PTV54',
     'Mandible in PTV60',
     'Mandible in PTV65',
     'Mandible in R+LT PTV65',
     'Mandible planner',
     'Mandible planner - PTV65 N +',
     'Mandible planner and PTV65 N +',
     'Mandible_NE',
     'Medial Avoid',
     'Medial avoid',
     'Metal',
     'Metal Block',
     'Mid AVOID',
     'Mid Avoid',
     'Mid shell',
     'Middel shell',
     'Middle Ring',
     'Middle Shell',
     'Middle ring',
     'Middle shell',
     'Mouth Avoid',
     'Mouthbite',
     'N1',
     'N60 Shell',
     'N70 Shell',
     'NODE INNER',
     'NODE OUTER',
     'Neck Avoid',
     'Neck PTV60',
     'Nodal CTV 65',
     'Nodal GTV1',
     'Nodal GTV2',
     'Nodal PTV 65',
     'Node CTV_65',
     'Node Ring',
     'NodeCTV65',
     'Nodes L CTV65',
     'Nodes L GTV',
     'Nodes R CTV65',
     'Nodes R GTV',
     'Normal Tissue Avoid',
     'Normal tissue avoid',
     'Nose AVOID',
     'OFOV',
     'OPT L cochlea',
     'OPT L lens',
     'OPT Lt Cochlea',
     'OPT Lt Globe',
     'OPT Lt Lens',
     'OPT Lt cochlea',
     'OPT Lt eye',
     'OPT PHARYN_CONST',
     'OPT Phar const - PTV',
     'OPT R cochlea',
     'OPT R lens',
     'OPT Rt Cochlea',
     'OPT Rt Globe',
     'OPT Rt Lens',
     'OPT Rt cochlea',
     'OPT Rt eye',
     'OPT left cochlea',
     'OPT right cochlea',
     'OPTIC AVIOD',
     'OPTIC AVOID',
     'OPTIC BLOCK',
     'OPTIC NERVE LEFT',
     'OPTIC NERVE RIGHT',
     'OPTICS AVOID',
     'OPTICS BLOCK',
     'ORAL_CAVITY',
     'OUTER 54',
     'OUTER 60',
     'OUTER 70',
     'OUTER L 60',
     'OUTER LT',
     'OUTER R 60',
     'OUTER RING',
     'OUTER RING PTV54',
     'OUTER RING PTV54 LT',
     'OUTER RING PTV54 RT',
     'OUTER RING PTV60 LN',
     'OUTER RING PTV60 LT',
     'OUTER RING PTV60 RT',
     'OUTER RING ptv60',
     'OUTER RT',
     'OUTER SHELL',
     'OVERLAP',
     'Optic Avoid',
     'Optic Block',
     'Optic Chiasm',
     'Optic ChiasmPRV',
     'Optic Nerves PRV',
     'Optic NervesPRV',
     'Optic avoid',
     'Optic chiasm',
     'Optic chiasm PRV',
     'Optic chiasm prv',
     'Optic nerve Lt',
     'Optic nerve Lt PRV',
     'Optic nerve Rt',
     'Optic nerve Rt prv',
     'OpticNerve',
     'Optics',
     'Optics Avoid',
     'Optics Block',
     'Optics avoid',
     'Optics block',
     'Optict Avoid',
     'Orbit block',
     'Oropharynx  SLD - teachi',
     'Oropharynx CTV60',
     'Oropharynx PTV60',
     'Outer 54',
     'Outer 60',
     'Outer 60 ring',
     'Outer LT ring',
     'Outer RT ring',
     'Outer Ring',
     'Outer Ring 54',
     'Outer Ring 60',
     'Outer Shell',
     'Outer Shell60',
     'Outer ring',
     'Outer shell',
     'Outer shell 54',
     'Outer shell-60L',
     'Outer shell-60R',
     'Outer-54L',
     'Outer-54L_2',
     'Outer-54R',
     'Outer-60',
     'Outer54R',
     'Outershell 54 R',
     'Outershell-60',
     'Outside ring border',
     'P - 1cm exp SLD - teachi',
     'P - teaching',
     'PACEMAKER',
     'PAROTID DUMMY',
     'PAROTID LT-PTV',
     'PAROTID R- PTV',
     'PAROTID RIGHT',
     'PAROTID Rt -PTV60',
     'PAROTID_L',
     'PAROTID_L - PTV',
     'PAROTID_L - PTVs',
     'PAROTID_L -PTV54',
     'PAROTID_L -PTVs',
     'PAROTID_L- PTV',
     'PAROTID_L-PTV',
     'PAROTID_L-PTV-60',
     'PAROTID_L1',
     'PAROTID_L_SP',
     'PAROTID_L_SP - PTV',
     'PAROTID_L_SP - PTV60',
     'PAROTID_L_SP -ptv',
     'PAROTID_R',
     'PAROTID_R - PTV',
     'PAROTID_R- PTV-54 R',
     'PAROTID_R- PTVs',
     'PAROTID_R-PTV',
     'PAROTID_R-PTVs',
     'PAROTID_R1',
     'PAROTID_R_',
     'PAROTID_R_-PTV60',
     'PAROTID_R_SP',
     'PAROTID_R_SP - PTV',
     'PCTV65',
     'PET pos disease',
     'PET pos disease_1',
     'PGTV65',
     'PHARYNX-PTVs',
     'PHARYN_CONS-PTV',
     'PHARYN_CONST',
     'PHARYN_CONST - PTV',
     'PHARYN_CONST- PTV',
     'PHARYN_CONST-PTV',
     'PHARYN_CONST-PTVs',
     'PHARYN_CONST_OPT',
     'PHARYN_CONST_SP',
     'PHARYN_CONST_SP - PTV',
     'PHARYN_CONST_SP - PTV60',
     'PHARYN_CONST_SP - T1',
     'PHARYN_CONST_SP - Y',
     'PHARYN_CONST_SP - temp1',
     'PHARYN_CONST_old',
     'PHARYN_SP - PTVs',
     'PLANNING BOLUS',
     'POST AVOID',
     'POST BLK',
     'PRETEND BOLUS',
     'PRV B stem',
     'PRV BRAIN STEM',
     'PRV BRAINSTEM',
     'PRV BRAINSTEM - ptv 1mm',
     'PRV BRAINSTEM and PTV',
     'PRV BRAINSTEM in PTV',
     'PRV BRAINSTEM-PTV',
     'PRV BRAINSTEM_old',
     'PRV BS',
     'PRV Brain Stem',
     'PRV Brain stem',
     'PRV Brainstem',
     'PRV Brainstem in PTV60',
     'PRV Bstem',
     'PRV CHIASM',
     'PRV CORD',
     'PRV Chiasm',
     'PRV Cord',
     'PRV Cord in PTV60',
     'PRV L COCHLEA',
     'PRV L Cochlea',
     'PRV L GLOBE',
     'PRV L Globe',
     'PRV L LENS',
     'PRV L Lens',
     'PRV L OPTIC N',
     'PRV L OPTIC N - ptv 1mm',
     'PRV L OPTIC N and PTV',
     'PRV L Optic Nerve',
     'PRV L Optic nerve',
     'PRV L eye',
     'PRV L globe',
     'PRV L lens',
     'PRV L op nerve',
     'PRV L optic nerve',
     'PRV LCochlea',
     'PRV LGlobe',
     'PRV LON',
     'PRV LON TARGET',
     'PRV LT LENS',
     'PRV LT LENS KK',
     'PRV LT ON',
     'PRV LT OPTIC',
     'PRV LT ORBIT',
     'PRV Lcochlea',
     'PRV Llens',
     'PRV LopticN',
     'PRV Lt Globe',
     'PRV Lt Lens',
     'PRV Lt Optic Nerve',
     'PRV LtCochlea',
     'PRV LtEye',
     'PRV LtGlobe',
     'PRV LtLens',
     'PRV LtOpticNerve',
     'PRV OC',
     'PRV OC and PTV(55Gy)',
     'PRV OPTIC CHIASM',
     'PRV Optic Chiasm',
     'PRV PITUATRY',
     'PRV Pituitary',
     'PRV R COCHLEA',
     'PRV R Cochlea',
     'PRV R GLOBE',
     'PRV R Globe',
     'PRV R LENS',
     'PRV R Lens',
     'PRV R OPTIC N',
     'PRV R OPTIC N - ptv 1mm',
     'PRV R OPTIC N and PTV',
     'PRV R Optic Nerve',
     'PRV R Optic nerve',
     'PRV R eye',
     'PRV R lens',
     'PRV R optic nerve',
     'PRV RCochlea',
     'PRV RGlobe',
     'PRV RON',
     'PRV RON and PTV(55Gy',
     'PRV RT LENS',
     'PRV RT LENS KK',
     'PRV RT ON',
     'PRV RT OPTIC',
     'PRV RT ORBIT',
     'PRV RT parotid',
     'PRV Rcochlea',
     'PRV Rlens',
     'PRV RopticN',
     'PRV Rt Cochlea',
     'PRV Rt Globe',
     'PRV Rt Lacrimal',
     'PRV Rt Lens',
     'PRV Rt Optic Nerve',
     'PRV Rt op nerve',
     'PRV RtCochlea',
     'PRV RtEye',
     'PRV RtGlobe',
     'PRV RtLens',
     'PRV RtOpticNerve',
     'PRV SPINAL CORD',
     'PRV SPINAL_CANAL',
     'PRV SPINAL_CORD',
     'PRV Spinal Canal',
     'PRV Spinal Cord',
     'PRV Spinal cord',
     'PRV b stem',
     'PRV brain stem',
     'PRV brainstem',
     'PRV bstem',
     'PRV chiasm',
     'PRV cord',
     'PRV l cochlea',
     'PRV l eye',
     'PRV l lens',
     'PRV left optic nerve',
     'PRV metal',
     'PRV optic chiasm',
     'PRV pit',
     'PRV pituitary',
     'PRV r eye',
     'PRV r lens',
     'PRV right optic nerve',
     'PRV spinal cord',
     'PRV stem',
     'PRV-est chiasm',
     'PRVBS',
     'PRVBStem - PTV',
     'PRVBrainstem',
     'PRVCord',
     'PRVCord - PTV',
     'PRVLeft optic nerve',
     'PRVLeft optic nerve -PTV',
     'PRVRight optic nerve',
     'PRVRight optic nerve -PTV',
     'PRVSpinalCord',
     'PRVbrainstem',
     'PRVspinal cord',
     'PS Cochlea left',
     'PS Cochlea right',
     'PSCochleaRight',
     'PScochlealeft',
     'PTV',
     'PTV  60Gy L',
     'PTV  60Gy L lower',
     'PTV  T 60',
     'PTV 50',
     'PTV 54',
     'PTV 54 L',
     'PTV 54 L neck',
     'PTV 54 Left neck',
     'PTV 54 R',
     'PTV 54 R neck',
     'PTV 54 Right',
     'PTV 54Gy',
     'PTV 54Gy_1',
     'PTV 55',
     'PTV 60',
     'PTV 60 + PTV 60 R nodes',
     'PTV 60 L',
     'PTV 60 OP',
     'PTV 60 R',
     'PTV 60 R nodes',
     'PTV 60 and PRVChiasm',
     'PTV 60 and PRVLON',
     'PTV 60 and PRVRON',
     'PTV 60 and R parotid',
     'PTV 60 clipped',
     'PTV 60 node',
     'PTV 60 ring',
     'PTV 60(excl Optics &edit)',
     'PTV 60Gy',
     'PTV 60R',
     'PTV 60p',
     'PTV 65',
     'PTV 65L',
     'PTV 65L B',
     'PTV 68',
     'PTV 68Gy',
     'PTV 70',
     'PTV 80',
     'PTV L 54',
     'PTV L 60',
     'PTV L54',
     'PTV LN 65',
     'PTV LN65',
     'PTV Lt neck 54',
     'PTV Lt neck 60',
     'PTV Lt54',
     'PTV Lt60',
     'PTV LtN 54',
     'PTV LtN 60',
     'PTV LtN 65',
     'PTV N',
     'PTV N 54 Lt',
     'PTV N 54 R',
     'PTV N 54 Sup',
     'PTV N 60',
     'PTV N 60 L',
     'PTV N 70',
     'PTV N60 L',
     'PTV N65',
     'PTV OP 60',
     'PTV P 65',
     'PTV P60',
     'PTV P65',
     'PTV R 54',
     'PTV R 60',
     'PTV R neck 60',
     'PTV R60',
     'PTV RLN60',
     'PTV RN65',
     'PTV Rt neck 54',
     'PTV Rt54',
     'PTV Rt60',
     'PTV RtN 60',
     'PTV RtN 65',
     'PTV T 60',
     'PTV T 65',
     'PTV T60',
     'PTV T70',
     'PTV for p/bolus',
     'PTV in air',
     'PTV l op nerve',
     'PTV node 70',
     'PTV op chiasm',
     'PTV p70',
     'PTV r op nerve',
     'PTV t 60',
     'PTV t 65',
     'PTV-54L',
     'PTV-54R2',
     'PTV-65N',
     'PTV-65T',
     'PTV-LN65 Lt',
     'PTV-LN65 Rt',
     'PTV-N 65',
     'PTV-N54L',
     'PTV-N54R',
     'PTV-N60',
     'PTV-N60 Left',
     'PTV-N65',
     'PTV-N65 post',
     'PTV-P60',
     'PTV-P65',
     'PTV-T60',
     'PTV-T65',
     'PTV12tongue',
     'PTV50',
     'PTV50 LT',
     'PTV50 RT',
     'PTV50 outer ring',
     'PTV50 ring',
     'PTV50Lt',
     'PTV50Rt',
     'PTV54',
     'PTV54  l neck_old',
     'PTV54 - PTV 60',
     'PTV54 BOTH',
     'PTV54 COMBINED',
     'PTV54 L',
     'PTV54 L 2',
     'PTV54 L Neck',
     'PTV54 L Neck Nodes',
     'PTV54 L OUTTER RING',
     'PTV54 L neck',
     'PTV54 L1',
     'PTV54 LN4',
     'PTV54 LN5',
     'PTV54 LT',
     'PTV54 LT INNER RING',
     'PTV54 LV11',
     'PTV54 Lt',
     'PTV54 R',
     'PTV54 R Neck',
     'PTV54 R Neck nodes',
     'PTV54 R neck',
     'PTV54 RT',
     'PTV54 RT ANT',
     'PTV54 RT OUTER RING',
     'PTV54 RT POST',
     'PTV54 RT SUP',
     'PTV54 RT inner ring',
     'PTV54 RT2',
     'PTV54 RT2 RING',
     'PTV54 Rt',
     'PTV54 Rt Neck',
     'PTV54 Split',
     'PTV54 b',
     'PTV54 ring',
     'PTV54+2',
     'PTV54-All',
     'PTV54-L',
     'PTV54-LEFT',
     'PTV54-LNECK',
     'PTV54-R',
     'PTV54-RIGHT-IV',
     'PTV54-RIGHT-V',
     'PTV54-RNECK',
     'PTV54-R_level V',
     'PTV54Buffer',
     'PTV54L',
     'PTV54L1',
     'PTV54L2',
     'PTV54L2 GB',
     'PTV54L3',
     'PTV54LT',
     'PTV54L_2',
     'PTV54Lb',
     'PTV54Lcomb',
     'PTV54Lt',
     'PTV54R',
     'PTV54R-3',
     'PTV54R1',
     'PTV54R2',
     'PTV54R2 GB',
     'PTV54R3',
     'PTV54RT',
     'PTV54Rt',
     'PTV54_L',
     'PTV54_R',
     'PTV54l',
     'PTV54l ring',
     'PTV55',
     'PTV55 ring',
     'PTV60',
     'PTV60  Right neck',
     'PTV60 LN',
     'PTV60 LT',
     'PTV60 LT INNER RING',
     'PTV60 LT NECK',
     'PTV60 LT OUTER RING',
     'PTV60 Left',
     'PTV60 Lt',
     'PTV60 Lt Neck',
     'PTV60 N',
     'PTV60 N - INF POST',
     'PTV60 N ANT SUP',
     'PTV60 N ANT SUP + PTV60 T',
     'PTV60 Nodes',
     'PTV60 P',
     'PTV60 R Neck',
     'PTV60 RT',
     'PTV60 RT INNER RING',
     'PTV60 RT NECK',
     'PTV60 RT OUTER RING',
     'PTV60 Right',
     'PTV60 Ring',
     'PTV60 Rt',
     'PTV60 Rt Neck',
     'PTV60 T',
     'PTV60 T RING',
     'PTV60 TONSIL',
     'PTV60 and larynx',
     'PTV60 and left parotid',
     'PTV60 and mandible',
     'PTV60 inf',
     'PTV60 l neck',
     'PTV60 left neck',
     'PTV60 lower Rt',
     'PTV60 mid Neck',
     'PTV60 orop',
     'PTV60 orop + PTV60',
     'PTV60 prim',
     'PTV60 right neck',
     'PTV60 ring',
     'PTV60 sup',
     'PTV60(combined)',
     'PTV60(original)',
     'PTV60+1mm',
     'PTV60+2mm',
     'PTV60+5mm',
     'PTV60-L',
     'PTV60-LNECK',
     'PTV60-OP',
     'PTV60-OP + PTV60-LNE',
     'PTV60-R',
     'PTV60-T',
     'PTV60-VII',
     'PTV60Buffer',
     'PTV60Gy',
     'PTV60L',
     'PTV60L Neck',
     'PTV60L Ring',
     'PTV60Lt',
     'PTV60N',
     'PTV60OP',
     'PTV60OP + PTV60 LT',
     'PTV60R',
     'PTV60R  Ring',
     'PTV60R + PTV60T',
     'PTV60R GB',
     'PTV60R ring',
     'PTV60Rt',
     'PTV60T',
     'PTV60T GB',
     'PTV60_L',
     'PTV60_L Neck',
     'PTV60combined',
     'PTV60excl PTV65',
     'PTV60lneck',
     'PTV60p',
     'PTV60p ring',
     'PTV60primary',
     'PTV60rn',
     'PTV60s',
     'PTV65',
     'PTV65 + PTV65 LN',
     'PTV65 +2',
     'PTV65 - Node',
     'PTV65 L neck',
     'PTV65 LN',
     'PTV65 LN LT',
     'PTV65 LN RT',
     'PTV65 LT',
     'PTV65 LT2',
     'PTV65 Lt',
     'PTV65 N',
     'PTV65 N + PTV65 P',
     'PTV65 N + PTV65 T',
     'PTV65 Node',
     'PTV65 P',
     'PTV65 R',
     'PTV65 R LN2',
     'PTV65 R LN2 + PTV65 RN',
     'PTV65 RN',
     'PTV65 RT',
     'PTV65 Rt',
     'PTV65 T',
     'PTV65 T + PTV65 N',
     'PTV65 TONSIL',
     'PTV65 ant',
     'PTV65 combined',
     'PTV65 post',
     'PTV65 ring',
     'PTV65-LN',
     'PTV65-N',
     'PTV65-R-N2',
     'PTV65-T',
     'PTV65-T + PTV65-N',
     'PTV65-primary',
     'PTV65L',
     'PTV65LN',
     'PTV65LN GB',
     'PTV65LN RT',
     'PTV65Lt',
     'PTV65LtN',
     'PTV65N Lt Neck',
     'PTV65R',
     'PTV65Rt',
     'PTV65RtN',
     'PTV65T',
     'PTV65T + PTV65LN',
     'PTV65T + PTV65LN L',
     'PTV65T GB',
     'PTV65_L_N',
     'PTV65_R_N',
     'PTV65left neck',
     'PTV65n',
     'PTV65node',
     'PTV68',
     'PTV68 LT',
     'PTV68 Left',
     'PTV68 Lt',
     'PTV68 Primary',
     'PTV68 RT',
     'PTV68 Right',
     'PTV68 Rt',
     'PTV68L',
     'PTV68L Ring',
     'PTV68R',
     'PTV68R Ring',
     'PTV68Ring',
     'PTV68neck',
     'PTV6Gy',
     'PTV70',
     'PTVB65',
     'PTVBuffer',
     'PTVL LN54',
     'PTVLt54',
     'PTVLtN54',
     'PTVLtN60',
     'PTVN 54 R',
     'PTVN 54R',
     'PTVN 65',
     'PTVN54L',
     'PTVN54_sjj',
     'PTVN60',
     'PTVN60 R',
     'PTVN65',
     'PTVN65_SJJ',
     'PTVP60',
     'PTVP65',
     'PTVRt54',
     'PTVRtN54',
     'PTVT65',
     'PTV_N_54',
     'PTV_N_60',
     'PTV_N_L2_65',
     'PTV_N_L_65',
     'PTV_N_R65',
     'PTVn 70',
     'PTVnode65',
     'PTVr60',
     'PTVr60 ring',
     'PTVs+1',
     'PTVs+1mm',
     'PTVs60',
     'PTVshell',
     'Pace maker',
     'Pace maker Avoid',
     'Parotid L',
     'Parotid L - PTV',
     'Parotid L -PTV',
     'Parotid Lt',
     'Parotid Lt - PTV',
     'Parotid Lt-PTV2mm',
     'Parotid R',
     'Parotid R - PTV',
     'Parotid R - PTV60',
     'Parotid R - PTVs',
     'Parotid R -PTV',
     'Parotid Rt',
     'Parotid Rt - PTV',
     'Parotid Rt in PTV',
     'Parotid Rt outside PTV',
     'Parotid Rt-PTV2mm',
     'Parotid left',
     'Parotid left - PTV',
     'Parotid left -PTV54L',
     'Parotid left -PTV65',
     'Parotid right',
     'Parotid right - PTV',
     'Parotid right - PTV54',
     'Parotid right - PTV60',
     'Periferal shell',
     'Periferral54',
     'Periferrral 54',
     'Perifferal shell',
     'PharynCon - PTV',
     'Pharyngeal - PTV',
     'Pharyngeal const - PTV',
     'Pharynx',
     'Pharynx - PTV',
     'Pit OPT',
     'Pituatary',
     'Pituitary',
     'Pituitary OPT',
     'Pituitary Opt',
     'Pituitary PRV',
     'Pituitary b',
     'PlStr Eye Lt',
     'PlStr Eye Rt',
     'PlStr L Globe',
     'PlStr L Lens',
     'PlStr R Globe',
     'PlStr R Lens',
     'Plan Bolus',
     'Planning  Bolus',
     'Planning Bolus',
     'Planning blous',
     'Planning bolus',
     'Planningbolus',
     'Planningl bolus',
     'Post AVOID',
     'Post Avoid',
     'Post Block',
     'Post Spine',
     'Post avoid',
     'Post avoid(lower)',
     'Post avoid(upper)',
     'Post block',
     'Post/Rt avoid',
     'Pre OP GTV',
     'Pre op GTV',
     'Pre-op GTV_P',
     'Pre-op tumour site',
     'PreCTV Surgical bed',
     'Pretend Bolus',
     'Pretend bolus',
     'Primary CTV_60',
     'Primary CTV_65',
     'Primary GTV',
     'Primary GTV + 5mm',
     'Ptv 65',
     'R  parotid',
     'R  parotid - PTV',
     'R Avoid',
     'R CTV54',
     'R CTV54 b',
     'R CTV60',
     'R CTV68',
     'R CTV68 b',
     'R Cochlea',
     'R Cochlea + 3mm',
     'R Cochlea Opt',
     'R CochleaPRV',
     'R Cochlear',
     'R Cochlear Avoid',
     'R Cochlear SLD',
     'R Globe',
     'R Globe OPT',
     'R Globe Opt',
     'R Globe PRV',
     'R Globe PS',
     'R Globe prv',
     'R Inf avoid',
     'R Lacrimal',
     'R Lens',
     'R Lens Avoid',
     'R Lens OPT',
     'R Lens Opt',
     'R Lens PRV',
     'R Lens PS',
     'R Lens opt',
     'R LensPRV',
     'R Lens_1',
     'R Lense OPT',
     'R Neck CTV54',
     'R Neck CTV54 - sjj',
     'R Neck CTV60',
     'R Neck PTV54',
     'R Neck PTV60',
     'R ON',
     'R ON PRV',
     'R Optic Nerve',
     'R Optic Nerve PRV',
     'R Optic Nerve PRV -  PTV70',
     'R Optic Nerve PRV and PTV70',
     'R Optic nerve',
     'R Orbit',
     'R PTV 54',
     'R PTV 60',
     'R PTV n 65',
     'R PTV12',
     'R PTV54',
     'R PTV54 - PTV60',
     'R PTV60',
     'R PTV68 b',
     'R Parotid',
     'R Parotid - PTV',
     'R Parotid - PTV54',
     'R Parotid - PTV60',
     'R Parotid - PTVs',
     'R Parotid -PTV',
     'R Parotid in PTV',
     'R Parotid-PTV',
     'R Ring 60',
     'R SMG',
     'R SMG - PTV',
     'R SUB gland-RT LN PTV',
     'R SUBMANDIBULAR',
     'R Sub mnd',
     'R Sub mnd - PTVs',
     'R Submand - PTV',
     'R Submandibular',
     'R Submandibular - PTV60',
     'R cochlea',
     'R cochlea Avoid',
     'R cochlea OPT',
     'R cochlea PRV',
     'R cochlea PS',
     'R cochlea avoid',
     'R cochlea opt',
     'R cochlea ps',
     'R cochlea2',
     'R cochlear',
     'R cochlear AVOID',
     'R cochlear OPT',
     'R cochlear Opt',
     'R cochlear PS',
     'R cochlear opt',
     'R cochlear ps',
     'R eye',
     'R eye Avoid',
     'R globe',
     'R globe AVOID',
     'R globe Avoid',
     'R globe PS',
     'R globe PS - PTV',
     'R globe PS and PTV(45G',
     'R globe prv',
     'R globe ps',
     'R globeOPT',
     'R lacrimal',
     'R lacrimal Avoid',
     'R lacrimal OPT',
     'R lacrimal galnd',
     'R lacrimal gland',
     'R lens',
     'R lens AVOID',
     'R lens Avoid',
     'R lens Avoid large',
     'R lens PRV',
     'R lens PS',
     'R lens prv',
     'R lensOPT',
     'R neck',
     'R neck + GTV + 15',
     'R neck CTV60',
     'R neck CTV60 b',
     "R neck Ib-V (+RP's)",
     'R neck PTV60 b',
     'R neck nodes',
     'R neck nodes II-V',
     'R neck nodes Ib',
     'R o nerve',
     'R op N',
     'R opt n PRV and PTV 60',
     'R optic nerve',
     'R optic nerve PRV',
     'R optic nerve prv',
     'R optic nervePRV',
     'R otpic nerve',
     'R otpic nerve PRV',
     'R parotid',
     'R parotid -  ptv54',
     'R parotid - All PTV',
     'R parotid - All PTV 60',
     'R parotid - PTV',
     'R parotid - PTV 60',
     'R parotid - PTV-54-R',
     'R parotid - PTV-60',
     'R parotid - PTV54',
     'R parotid - PTV60',
     'R parotid - PTVs',
     'R parotid -PTV',
     'R parotid -PTV54R',
     'R parotid -PTV60',
     'R parotid -ptv60',
     'R parotid and PTV',
     'R parotid and PTV54',
     'R parotid avoid',
     'R parotid b',
     'R parotid inPTV60',
     'R parotid-PTV',
     'R parotid_old',
     'R ring 60',
     'R smg',
     'R sub - PTV',
     'R sub mand gland',
     'R sub mandibular',
     'R sub-PTV',
     'R submadibular',
     'R subman - PTV',
     'R submand - PTV',
     'R submand -PTV65',
     'R submand IN PTV65',
     'R submandib',
     'R submandib - PTV',
     'R submandib -PTV',
     'R submandibular',
     'R submandibular - PTV',
     'R submandibular - PTVs',
     'R submandibular galnd',
     'R submandibular gland',
     'R submandibular-PTV',
     'R submandidular',
     'R submandidular -PTVs',
     'R sum mandib',
     'R temp lobe',
     'R temporal lobe',
     'R tonsil bed',
     'RAvoid',
     'RCTV60',
     'RCTVnode65',
     'RGTVnode65',
     'RIGHT EYE',
     'RING',
     'RING 54 LT',
     'RING LT PTV50',
     'RING LT PTV54',
     'RING PTV54',
     'RING PTV54 L2',
     'RING PTV54 LT',
     'RING PTV54 R2',
     'RING PTV54 RT',
     'RING PTV54 RT - R2 - T2',
     'RING PTV54 RT ANT',
     'RING PTV54 RT ANT_1',
     'RING PTV54 SUP',
     'RING PTV54 l3',
     'RING PTV54L1',
     'RING PTV54R',
     'RING PTV54R 3',
     'RING PTV54R1',
     'RING PTV54_4',
     'RING PTV54_5',
     'RING PTV55',
     'RING PTV60',
     'RING PTV60 L',
     'RING PTV60 LN',
     'RING PTV60 LT',
     'RING PTV60P',
     'RING PTV65',
     'RING PTV65 ANT',
     'RING PTV65 POST',
     'RING RT PTV50',
     'RING RT PTV60',
     'RIght submandibular',
     'RN PTV54',
     'RON PRV',
     'RPTV54',
     'RPTV60',
     'RPTVn65',
     'RParotid - PTV',
     'RSubGland - PTV',
     'RT AVOID',
     'RT Avoid',
     'RT COCHLEA OPT',
     'RT GLOBE',
     'RT LENS KK',
     'RT LN PTV',
     'RT LN PTV 54',
     'RT LN PTV 60',
     'RT LN PTV54',
     'RT LN PTV60',
     'RT OPTIC NERVE PRV',
     'RT PAROTID',
     'RT PAROTID - PTV',
     'RT PTV 60',
     'RT PTV 68',
     'RT PTV60',
     'RT PTV65',
     'RT SHELL 60',
     'RT SHELL 68',
     'RT SHOULDER BLOCK',
     'RT SUBMANDBLR',
     'RVR',
     'Ravoid',
     'Rcochlea',
     'Rcochlea OPT',
     'Rctvnodes60',
     'Real Bolus',
     'Remaining normal tissue',
     'Right  lens',
     'Right  lens PRV',
     'Right Globe',
     'Right GlobePRV',
     'Right Lens',
     'Right Lung',
     'Right PAROTID',
     'Right PAROTID-PTV60',
     'Right Parotid',
     'Right Parotid  - PTV',
     'Right SMG',
     'Right SMG - PTV',
     'Right cochlea',
     'Right cochlea Avoid',
     'Right cochlea OPT',
     'Right eye',
     'Right globe',
     'Right globe PRV',
     'Right globe PS',
     'Right globe PS - PTV 60',
     'Right globePRV',
     'Right lens',
     'Right lens PRV',
     'Right lens PS',
     'Right neck CTV 54',
     'Right neck CTV54',
     'Right optic nerve',
     'Right optic nerve PRV',
     'Right parotid',
     'Right parotid - PTV',
     'Right parotid - PTV60R',
     'Right submandibular',
     'Right submandibular AJ',
     'Right submndblr gland',
     'RightParotid',
     'Rightnodes-54',
     'Ring',
     'Ring 1',
     'Ring 2',
     'Ring 3',
     'Ring 50',
     'Ring 54',
     'Ring 54 L',
     'Ring 54 Left',
     'Ring 54 R',
     'Ring 54 Right',
     'Ring 55',
     'Ring 60',
     'Ring 60 L',
     'Ring 60 Left',
     'Ring 60 Neck',
     'Ring 60 T',
     'Ring 60 lower Rt',
     'Ring 65',
     'Ring 65 N',
     'Ring 65 P',
     'Ring 70',
     'Ring L 54',
     'Ring L 60',
     'Ring L 65',
     'Ring LN 60',
     'Ring LN65',
     'Ring Lt 60',
     'Ring Lt PTV54',
     'Ring Lt PTV60',
     'Ring Lt PTV65',
     'Ring Lt54',
     'Ring Lt54 - 60',
     'Ring Lt60',
     'Ring LtN 60',
     'Ring LtN 65',
     'Ring N65',
     'Ring Nodes 65',
     'Ring OP 60',
     'Ring OP PTV60',
     'Ring Outer',
     'Ring P60',
     'Ring P65',
     'Ring PTV 54R3',
     'Ring PTV LN65 Lt',
     'Ring PTV LN65 Rt',
     'Ring PTV P60',
     'Ring PTV P65',
     'Ring PTV54',
     'Ring PTV54Lcomb',
     'Ring PTV54R',
     'Ring PTV54R2',
     'Ring PTV60',
     'Ring PTV60 Lt',
     'Ring PTV60 Rt',
     'Ring PTV60R',
     'Ring PTV65',
     'Ring PTV68',
     'Ring R 60',
     'Ring RN 54',
     'Ring RN65',
     'Ring Rt',
     'Ring Rt 54',
     'Ring Rt PTV54',
     'Ring Rt PTV60',
     'Ring Rt PTV65',
     'Ring Rt60',
     'Ring RtN 60',
     'Ring RtN 65',
     'Ring nodal',
     'Ring p 65',
     'Ring1',
     'Ring2',
     'Ring3',
     'Ring54',
     'Ring54L',
     'Ring54Lt',
     'Ring54R',
     'Ring54Rt',
     'Ring54outer',
     'Ring55',
     'Ring60',
     'Ring60 1',
     'Ring60 2',
     'Ring60 Lt',
     'Ring60 Rt',
     'Ring60Lt',
     'Ring60N',
     'Ring60Rt',
     'Ring60T',
     'Ring60outer',
     'Ring65',
     'Ring65 RtN',
     'Ring65LN',
     'Ring65Lt',
     'Ring65Rt',
     'Ring68',
     'Ring68 Rt',
     'Ring68Lt',
     'Ring70',
     'RingB65',
     'RingLt',
     'RingLt54',
     'RingLtN54',
     'RingN60',
     'RingN65',
     'RingP60',
     'RingP65',
     'RingRt',
     'RingRt54',
     'RingT65',
     'Rlens',
     'RlensOPT',
     'Rneck nodes PTV54',
     'Rnecknodes PTV60',
     'Rparotid - PTV',
     'Rpost avoid',
     'Rt 54 Ring',
     'Rt 54N Shell',
     'Rt 54ring',
     'Rt Avoid',
     'Rt CTV 54',
     'Rt Cochlea',
     'Rt Cochlea AVOID',
     'Rt Cochlea Opt',
     'Rt Cochlea PRV',
     'Rt Eye',
     'Rt Globe',
     'Rt Globe Opt',
     'Rt Globe PRV',
     'Rt Globe PRV - PTV',
     'Rt Globe PRV in PTV',
     'Rt Lacrimal Gland Opt',
     'Rt Lacrimal Opt',
     'Rt Lens',
     'Rt Lens AVOID',
     'Rt Lens Opt',
     'Rt Lens PRV',
     'Rt Neck 54',
     'Rt ON PRV',
     'Rt ON PRV - PTV',
     'Rt OPT Cochlea',
     'Rt Optic Nerve',
     'Rt Optic Nerve PRV',
     'Rt Optic nerve PRV',
     'Rt Optic nerve PRV - PTV',
     'Rt Orbit Opt',
     'Rt Orbit Opt - PTV',
     'Rt Orbit Opt in PTV',
     'Rt PTV 54',
     'Rt PTV nodes60',
     'Rt PTV54',
     'Rt PTV60',
     'Rt PTV60N',
     'Rt Parotid',
     'Rt Parotid  - PTV',
     'Rt Parotid - PTV',
     'Rt Parotid outside PTV',
     'Rt Ring 60',
     'Rt Ring60',
     'Rt SM Gland',
     'Rt SMG',
     'Rt SMG - PTV',
     'Rt Shoulder Block',
     'Rt Shoulder block',
     'Rt Sub Man-PTV',
     'Rt SubmanG',
     'Rt SubmanG - PTV',
     'Rt Submandib',
     'Rt Submandibular',
     'Rt Submandibular - PTV',
     'Rt Submandibular Gland',
     'Rt avoid',
     'Rt eye',
     'Rt eye_PRV',
     'Rt lacrimal gland',
     'Rt lens',
     'Rt lensPRV',
     'Rt neck 60',
     'Rt neck PTV 54',
     'Rt nodes PTV54',
     'Rt optic nerve',
     'Rt optic nerve PRV',
     'Rt optic nervePRV',
     'Rt parotid',
     'Rt shoudler block',
     'Rt shoulder Block',
     'Rt shoulder block',
     'Rt shoulder blocks',
     'Rt sub and PTV54',
     'Rt subman-1mm',
     'Rt submandibular gland',
     'Rt54 RING',
     'RtCTV60',
     'RtPTV54',
     'RtPTV54 ring',
     'RtPTV60',
     'SC',
     'SC PRV',
     'SC PS',
     'SC block',
     'SHELL',
     'SHELL 1',
     'SHELL 54',
     'SHELL 60',
     'SHELL 60 OUTER',
     'SHELL 65',
     'SHELL 68',
     'SHELL LT',
     'SHELL LT LN',
     'SHELL LT OVERLAP',
     'SHELL LT PTV65',
     'SHELL OL',
     'SHELL RT',
     'SHELL RT LN',
     'SHELL RT PTV65',
     'SHELL1',
     'SHELL10',
     'SHELL2',
     'SHELL20',
     'SHELL3',
     'SHELL54',
     'SHELL60',
     'SHELL60 INNER',
     'SHELL65',
     'SHELL68',
     'SHELL70',
     'SHLDR BLOCKS',
     'SHOULDER AVOID',
     'SHOULDER BLK',
     'SHOULDER BLOCK',
     'SHOULDER BLOCK L',
     'SHOULDER BLOCK R',
     'SHOULDER BLOCKS',
     'SHOULDER BLOCKS 2',
     'SHOULDER BLOCKS L',
     'SHOULDER BLOCKS RT',
     'SKIN',
     'SKIN_SP',
     'SKIN_SP2',
     "SLD - keep but dont' plan",
     'SOFT_PALATE',
     'SPINAL CANAL PRV',
     'SPINAL CORD',
     'SPINAL CORD PRV',
     'SPINAL_CANAL',
     'SPINAL_CANAL PRV',
     'SPINAL_CANAL_OPT',
     'SPINAL_CANAL_PRV',
     'SPINAL_CANAL_SP',
     'SPINAL_CANAL_SP PR',
     'SPINAL_CANAL_SP PRV',
     'SPINAL_CORD',
     'SPINAL_CORD_',
     'SPINAL_CORDprv',
     'SPINAL_cord',
     'SPINAL_cord_SP',
     'SPINE BLOCK',
     'SUBMANDIBULAR L',
     'SUBMND_SALV_L1',
     'SUBMND_SALV_R1',
     'Scanning Circle Block',
     'Second shell 60',
     'Shel 60',
     'Shell',
     'Shell 54',
     'Shell 54-L',
     'Shell 54L',
     'Shell 54R',
     'Shell 54_1',
     'Shell 60',
     'Shell 60 RNeck',
     'Shell 60 T',
     'Shell 65',
     'Shell 65 Rt',
     'Shell 65-left',
     'Shell Inner',
     'Shell Outer',
     'Shell inner',
     'Shell outer',
     'Shell outer-54R',
     'Shell-54 L',
     'Shell-54 R',
     'Shell-54L',
     'Shell-54R',
     'Shell-60',
     'Shell-65',
     'Shell54L',
     'Shell60',
     'Shell68',
     'Shellinner-54R',
     'Shoulder Block',
     'Shoulder Block R',
     'Shoulder Blocks',
     'Shoulder block',
     'Shoulder block L',
     'Shoulder blocks',
     'ShoulderBlocks',
     'Skin',
     'Skin - outer ring',
     'Skin KK',
     'Skin2',
     'Spinal Block',
     'Spinal Canal PRV',
     'Spinal Cord',
     'Spinal Cord - sjj',
     'Spinal Cord PRV',
     'Spinal CordPRV',
     'Spinal block',
     'Spinal cord',
     'Spinal cord PRV',
     'Spinal cord SLD',
     'Spinal cordPRV',
     'SpinalCord',
     'SpinalCord PRV',
     'Spine',
     'Spine Avoid',
     'Spine Block',
     'Spine avoid',
     'Spine block',
     'Spine cord',
     'Spine+BStem Block',
     'SpinePRV',
     'Splitter avoid',
     'Stem PRV',
     'StemPRV',
     'StemPTV',
     'Subman Lt',
     'Subman Rt',
     'Submand left',
     'Submand left - PTV',
     'Submand left - PTV54-L',
     'Submand right',
     'Submand right (in PTV)',
     'Submand right - PTV',
     'Submand right - PTV60',
     'Submandibular L',
     'Submandibular L - PTV',
     'Submandibular Lt',
     'Submandibular R',
     'Submandibular R - PTV',
     'Submandibular Rt',
     'Submandibular gland Lt',
     'Submandibular gland Rt',
     'Sup N54 Shell',
     'Sup avoid',
     'Surgical bed',
     'Surgical bed CTV',
     'T1',
     'T1 60',
     'T1 L',
     'T1 R',
     'T3',
     'T4',
     'T60 Shell',
     'T70 shell',
     'TEMP',
     'THYROID',
     'TISSUE',
     'TREATMENT BOLUS',
     'TT1',
     'TT2',
     'Teeth',
     'Teeth Artefacts',
     'Teeth Block',
     'Teeth artefacts',
     'Temp',
     'Temp Combined',
     'Temp for p/bolus',
     'Temp1',
     'Throat Avoid',
     'Thyroid outside PTVs',
     'Tongue',
     'Tonsillar bed L',
     'Treatment bolus',
     'Tumour CTV 60',
     'VIRTUAL BOLUS',
     'Virtual Bolus',
     'Virtual bolus',
     'Wax',
     'air',
     'air and PTV70',
     'air density in ptv',
     'air in LtPTV54',
     'air in PTV',
     'air in PTV65',
     'air in RtPTV54',
     'air in ptv',
     'air in ptv+5mm',
     'all PTV',
     'all PTVs',
     'all ptv',
     'ant',
     'ant avoid',
     'ant block',
     'artefact',
     'artefact = 1',
     'artefact D=1',
     'artefact block',
     'artefact density 1',
     'artefact density O/R',
     'artefact-low dens',
     'artefacts',
     'artifact',
     'avoid',
     'avoid ant',
     'avoid cord',
     'avoid post',
     'avoid sbmd',
     'avoid2',
     'b stem',
     'b stem PRV',
     'b stemPRV',
     'b3',
     'block',
     'blocks breast',
     'body',
     'bolus required',
     'brain stem',
     'brain stem PRV',
     'brain stem prv',
     'brain stemPRV',
     'brainstem',
     'brainstem AVOID',
     'brainstem PRV',
     'brainstem PRV - PTV',
     'brainstem prv',
     'brainstem- sjj',
     'brainstemPRV',
     'brainstemsjj',
     'braisntem',
     'bstem',
     'bstem PRV and PTV 60',
     'bstem PRV and PTV p70',
     'buffer',
     'c2',
     'central avoid',
     'chiasm',
     'chiasm PRV',
     'chiasm in ptv',
     'chiasm out ptv',
     'chiasm prv',
     'chiasmPRV',
     'clipped ctv60',
     'cochlea -l',
     'cochlea L',
     'cochlea L PRV',
     'cochlea avoid',
     'combined GTV',
     'combined PTV',
     'combined PTV 60',
     'combined PTVs',
     'contrast override',
     'cord',
     'cord Block',
     'cord PRV',
     'cord avoid',
     'cord block',
     'cord prv',
     'cordPRV',
     'couch',
     'couch Block',
     'ctV60',
     'ctv',
     'ctv  l neck 54',
     'ctv  l neck 54_old',
     'ctv  r neck 60',
     'ctv 54',
     'ctv 60',
     'ctv 60 nodesl',
     'ctv 65',
     'ctv 68',
     'ctv NL - 65 - sjj',
     'ctv l nodes 54',
     'ctv r nodes 60',
     'ctv tongue / node 68',
     'ctv10mm',
     'ctv168',
     'ctv268',
     'ctv50',
     'ctv50L',
     'ctv50R',
     'ctv54',
     'ctv54 - L',
     'ctv54 L',
     'ctv54 R',
     'ctv54-L',
     'ctv54-R',
     'ctv54R',
     'ctv54l',
     'ctv54lnsjj',
     'ctv55',
     'ctv60',
     'ctv60 + ctv60',
     'ctv60 - LN',
     'ctv60 SJJ',
     'ctv60 left neck',
     'ctv60 right neck',
     'ctv60- p',
     'ctv60- sjj',
     'ctv60--sjj',
     'ctv60-OP-sjj',
     'ctv60-R',
     'ctv60-l',
     'ctv60-p',
     'ctv60-sjj',
     'ctv60N-L-',
     'ctv60Rsjj',
     'ctv60_1',
     'ctv60l',
     'ctv60lneck',
     'ctv60lnr-sjj',
     'ctv60lnsjj',
     'ctv60n',
     'ctv60n-L',
     'ctv60nodesR',
     'ctv60op',
     'ctv60oropharynx',
     'ctv60p',
     'ctv60p-sjj',
     'ctv60r',
     'ctv60rn',
     'ctv60tongue',
     'ctv65',
     'ctv65 - p',
     'ctv65 - p - sjj',
     'ctv65-primary',
     'ctv65-rt n-sjj',
     'ctv65-sjj',
     'ctv65-sjj-l',
     'ctv65-sjj-r',
     'ctv65left neck',
     'ctv65n',
     'ctv65node',
     'ctv65node1',
     'ctv65node2',
     'ctv65p',
     'ctv65primary',
     'ctv65sjj',
     'ctv65sjjlarynx',
     'ctv68',
     'ctv68R',
     'ctv68_1',
     'ctv68l',
     'ctv68prmary',
     'ctv68r',
     'ctv70',
     'ctvL LN54',
     'ctvNP60',
     'ctvR-54',
     'ctvRLN60',
     'ctv_65',
     'ctvln-65',
     'ctvnode65',
     'ctvnodeL65',
     'ctvnodes60',
     'ctvp-65',
     'ctvp60',
     'ctvp65',
     'ctvparotid60',
     'ctvprimary65',
     'ctvr60',
     'ctvrn-65',
     'ctvsjj',
     'cvt65RN',
     'd2',
     'denisty overide',
     'density1',
     'density2',
     'do not use-dupl',
     'est chiasm- drawn by KW',
     'eye block',
     'filling',
     'fillings',
     'fillings saturation',
     'final GTV + 15mm',
     'fo p/bolus',
     'for bol',
     'for bolus',
     'for p-bolus',
     'for p/bol',
     'for virtual bolus',
     'g2',
     'globe L',
     'globe L PRV',
     'globe R',
     'globe R PRV',
     'gtv',
     'gtv 2013 pre Vsdg',
     'gtv mri',
     'gtv node65',
     'gtv node65_1',
     'gtv-65',
     'gtv-sjj 65',
     'gtv-sjj65n',
     'gtv1',
     'gtv2',
     'gtv65',
     'gtv65-sjj',
     'gtv65-sjj-l',
     'gtv65-sjj-r',
     'gtv65n',
     'gtv65p',
     'gtv65sjj',
     'gtv68',
     'gtv70',
     'gtvln-65',
     'gtvln68l',
     'gtvn-sjj-l65n',
     'gtvn65-r',
     'gtvn65-r-sjj',
     'gtvn68r',
     'gtvnasopharynx70',
     'gtvnl65',
     'gtvnode',
     'gtvnode65',
     'gtvnodeL65',
     'gtvp-65',
     'gtvp65',
     'gtvprimary',
     'gtvprimary65',
     'gtvrn-65',
     'gtvsjj',
     'gtvsjj65',
     'gvt',
     'gvt60p',
     'gvt65sjj',
     'high dose ring',
     'icru',
     'inf avoid',
     'inf block',
     'inner 54',
     'inner 60',
     'inner ring',
     'inner ring PTV54',
     'inner ring PTV60',
     'inner ring PTV65',
     'inner ring ptv lt',
     'inner ring ptv rt',
     'inner ring ptv54',
     'inner ring ptv54 4rt',
     'inner ring ptv54 lt',
     'inner ring ptv54 rt',
     'inner ring ptv60',
     'inner ring ptv60 t+ant sup',
     'inner ring ptv65',
     'inner rt',
     'inner shell',
     'inner60',
     'innr ring ptv60 inf post',
     'inv l nodes',
     'l  globe',
     'l Globe',
     'l cochlea',
     'l cochlea AVOID',
     'l cochlea Avoid',
     'l cochlea OPT',
     'l cochlea PRV',
     'l cochlea PS',
     'l cochlea opt',
     'l cochlea ps',
     'l cochleaOPT',
     'l cochlear',
     'l cochlearOPT',
     'l ctv nodes54',
     'l ctv54',
     'l ctv60',
     'l ctv65node',
     'l cvt60',
     'l eye',
     'l eye PRV',
     'l globe',
     'l globe Avoid',
     'l globe PRV',
     'l globe PS',
     'l gtv65node',
     'l lacrimal',
     'l lacrimal gland',
     'l lens',
     'l lens Avoid',
     'l lens PRV',
     'l neck - 54Gy',
     'l neck - PTV54Gy',
     'l neck nodes',
     'l neck nodes - 54',
     'l on',
     'l op nerve',
     'l optic nerve',
     'l optic nerve PRV',
     'l optic nerve prv',
     'l orbit',
     'l parotid',
     'l parotid - Lt PTV',
     'l parotid - PTV',
     'l parotid - PTV 54',
     'l parotid - PTV 60',
     'l parotid - PTV LLN54',
     "l parotid - PTV'S",
     'l parotid - PTV54',
     'l parotid - PTV54l',
     'l parotid - PTV60',
     'l parotid - ptv54',
     'l parotid - rptv65/60',
     'l parotid -PTV60Opt',
     'l parotid -PTV65',
     'l parotid -PTV65_1',
     'l parotid IN PTV 54',
     'l parotid and PTV 60',
     'l parotid in PTV',
     'l parotid in PTV60',
     'l parotid out PTV',
     'l prv globe in ptv',
     'l pvt60',
     'l salivary gland',
     'l sm gland',
     'l sm gland - PTV',
     'l smgland',
     'l smgland - PTV',
     'l submadibular',
     'l submand',
     'l submandib',
     'l submandibular',
     'l submandibular - PTV',
     'l submandibular gland',
     'l submandibular gland - P',
     'l temporal',
     'l temporal lobe',
     'lCTV54',
     'lacrimal gland left',
     'larynx',
     'larynx (OAR)',
     'larynx (OAR) - PTV',
     'larynx -  PTVs',
     'larynx - NODES',
     'larynx - PTV',
     'larynx - PTV54+PTV60',
     'larynx - PTVs',
     'larynx - RT LN PTV60',
     'larynx - ptv60s',
     'larynx -PTVs',
     'larynx PRV',
     'larynx avoid',
     'larynx in PTV',
     'larynx in RT LN PTV60',
     'lat avoid',
     'lcochlea',
     'lcochlea OPT',
     'lctv54',
     'lctv60',
     'lctv60n',
     'lctv65',
     'lctv65n',
     'lctvnodes',
     'lctvnodes60',
     'lctvnrp65',
     'lctvp65',
     'lcvt68',
     'left  parotid',
     'left ON PRV',
     'left SMG',
     'left SMG - PTV',
     'left SMG - PTV54L',
     'left VII, Ib, V & IV',
     'left avoid',
     'left cochlea',
     'left cochlea AVOID',
     'left cochlea OPT',
     'left cochlea PS',
     'left ctv 60',
     'left eye',
     'left eye PRV',
     'left globe',
     'left globe Avoid',
     'left globe PS',
     'left lacrimal gland',
     'left lens',
     'left lens PS',
     'left levels II & III',
     'left neck',
     'left neck CTV 60',
     'left neck IB-V',
     'left neck IB-V - CTV 60',
     'left neck II-Va',
     'left neck ctv 54',
     'left neck ctv 60',
     'left neck nodes ctv 60',
     'left nodes',
     'left optic nerve',
     'left optic nerve PRV',
     'left orbit',
     'left parotid',
     'left parotid - PTV',
     'left parotid - PTV 60',
     'left parotid - PTV L 60',
     'left parotid - PTV50 LT',
     'left parotid - PTV54',
     'left parotid - PTV54 LT',
     'left parotid - PTV54L',
     'left parotid - PTV60',
     'left parotid PRV',
     'left parotid and PTV60',
     'left shoulder block',
     'left subm gland',
     'left submamandibular glan',
     'left submand  gland',
     'left submand gl',
     'left submand gland',
     'left submandibular',
     'left submandibular g',
     'left submandibular gl',
     'left submandibular gland',
     'left sumandibular gland',
     'leftctv68',
     'leftctv68_1',
     'lens Left',
     'lens Right',
     'lens left',
     'lens lt',
     'lens right',
     'lens right OPT',
     'lens rt',
     'level4',
     'level5',
     'lgtv65',
     'lgtv65n',
     'lgtv68',
     'lgtvp65',
     'lgvnrp',
     'llat avoid',
     'lon',
     'lptv54',
     'lptv60',
     'lptv65n',
     'lptvnp65',
     'lptvp65',
     'lptvp65-t1',
     'lptvp65-t2',
     'lt SubmanG',
     'lt avoid',
     'lt cochlea',
     'lt cochlea PRV',
     'lt ctv65nodes',
     'lt eye',
     'lt gtv65',
     'lt gtv65_1',
     'lt opitc nerve',
     'lt parotid',
     'lt shoulder',
     'lt shoulder block',
     'lt sub - PTVs',
     'lt submand',
     'lt submand gland',
     'lt submandibular',
     'mandible',
     'mandible - PTV',
     'mandible - PTV60',
     'mandible - PTV65',
     'mandible - PTV65 N',
     'mandible - PTV65 R',
     'mandible - PTV65s',
     'mandible - ptv',
     'mandible - ptv60',
     'mandible AVOID',
     'mandible IN PTV 54',
     'mandible IN PTV 60',
     'mandible IN PTV60',
     'mandible and PTV60',
     'mandible and PTV65',
     'mandible and PTV65 N',
     'mandible and PTV65 R',
     'mandible and PTV65LN R + mandible',
     'mandible density',
     'mandible edit',
     'mandible in PTV',
     'mandible in PTV p70',
     'mandible in PTV60',
     'mandible in PTV60s',
     'mandible in PTV65',
     'mandible in PTV65 T',
     'mandible in both PTV65',
     'mandible in ptv65',
     'metal',
     'mid avoid',
     'mid ring',
     'middle avoid',
     'mouth avoid',
     'mouth tissue',
     'mouth_sinus avoid',
     'n3',
     "nadeera's outline",
     'neck avoid',
     'neck tissue',
     'nodal CTV 54',
     'node 70',
     'node+10',
     'nodea',
     'nodeb',
     'nodes L neck',
     'nodes R neck',
     'not in use',
     'not to be used',
     'not use',
     'not use2',
     'not used',
     'not used 2',
     'obturator',
     'old GTV',
     'old GTVN2',
     'old GTVN3',
     'old GTV_L_N',
     'op chiasm',
     'opt chiasm',
     'optic AVOID',
     'optic Chiasm',
     'optic Chiasm PRV',
     'optic block',
     'optic chiasm',
     'optic chiasm PRV',
     'optic chiasm prv',
     'optic chiasmPRV',
     'optic chiasmPRV - PTV70',
     'optic chiasmPRV and PTV70',
     'optic nerve prv',
     'optics',
     'optics avoid',
     'optics block',
     'orbit left',
     'orbit right',
     'oropharynx',
     'oropharynx + left leve',
     'other avoid',
     'outer 60',
     'outer Ring',
     'outer ring',
     'outer ring PTV54',
     'outer ring lt',
     'outer ring ptv rt',
     'outer ring ptv54',
     'outer ring ptv54 lt',
     'outer ring ptv54 rt',
     'outer ring ptv54rt',
     'outer ring ptv60',
     'outer ring ptv65',
     'outer rt',
     'outer shell',
     'outer54',
     'outer60',
     'outside block',
     'override',
     'pacemaker',
     'pacemaker AVOID',
     'pacemaker AVOID2',
     'pacemaker ring',
     'parotid L',
     'parotid R',
     'parotid left',
     'parotid left - PTV',
     'parotid right',
     'parotid right - PTV',
     'patient',
     'pb',
     'pit fossa',
     'pit fossa PRV',
     'pituiatry',
     'pituitary',
     'pituitary PRV',
     'pituitary ps',
     'pituitaryPRV',
     'piuitary',
     'planning Bolus',
     'planning bolus',
     'planningbolus',
     'post',
     'post Avoid',
     'post avoid',
     'post block',
     'post block inf',
     'post block sup',
     'post direct block',
     'post inf avoid',
     'post sup avoid',
     'post-op gtv',
     'post/inf avoid',
     'pre-op GTV',
     'pre-op GTV rt parotid',
     'pre-op GTV+10',
     'pre-op ctv',
     'pre-op gtv',
     'pre-op gtv - sjj',
     'pre-op level I nodes',
     'pre-op node',
     'pre-op parotid',
     'pre-opGTV',
     'pre-opgtv',
     'prechemoGTV',
     'pretend bolus',
     'primary CTV60',
     'prv cord',
     'prv l globe',
     'prv lt globe',
     'prv rt globe',
     'ptv',
     'ptv 1mm',
     'ptv 54 clipped',
     'ptv 60 clipped',
     'ptv 65',
     'ptv 68 clipped',
     'ptv nodes 68',
     'ptv54 L',
     'ptv54 R',
     'ptv60',
     'ptv60 lt inner ring',
     'ptv60 lt outer ring',
     'ptv60 rt inner ring',
     'ptv60 rt outer ring',
     'ptv60-sjj',
     'ptv60l',
     'ptv60l clipped',
     'ptv60n-L',
     'ptv60r clipped',
     'ptv65sjj',
     'ptv68',
     'ptvp65',
     'r  neck ctv 60',
     'r  neck ctv 68',
     'r cochlea',
     'r cochlea AVOID',
     'r cochlea Avoid',
     'r cochlea OPT',
     'r cochlea PRV',
     'r cochlea PS',
     'r cochlea opt',
     'r cochlea ps',
     'r cochlear',
     'r cochlear OPT',
     'r cocleaa',
     'r cocleaa AVOID',
     'r ctv nodes54',
     'r ctv54',
     'r ctv60',
     'r cvt60',
     'r eye',
     'r eye PRV',
     'r globe',
     'r globe Avoid',
     'r globe PRV',
     'r globe PS',
     'r gtv65',
     'r lacrimal',
     'r lacrimal gland',
     'r lens',
     'r lens Avoid',
     'r lens PRV',
     'r neck - 60Gy',
     'r neck CTV - 60Gy',
     'r neck nodes',
     'r node',
     'r on',
     'r op nerve',
     'r optic nerve',
     'r optic nerve PRV',
     'r optic nerve prv',
     'r orbit',
     'r parotid',
     'r parotid - PTV',
     'r parotid - PTV 60',
     'r parotid - PTV RLN60',
     "r parotid - PTV'S",
     'r parotid - PTV54',
     'r parotid - PTV60',
     'r parotid - PTV60rn',
     'r parotid - PTVN54',
     'r parotid - Rt PTV',
     'r parotid - ptv60',
     'r parotid - rptv65',
     'r parotid -PTV',
     'r parotid -PTV54',
     'r parotid -PTV60/65',
     'r parotid IN PTV60',
     'r parotid in ptv',
     'r parotid out PTV',
     'r ptv60',
     'r sm gland',
     'r sm gland - PTV',
     'r submand',
     'r submand gland',
     'r submandib',
     'r submandibular',
     'r submandibular - PTV',
     'r submandibular gl - PTV',
     'r submandibular gland',
     'r submandibular gland - PTV2',
     'r temporal lobe',
     'r3',
     'rCTV54',
     'rctv54',
     'rctv60',
     'rctv60n',
     'rctv60nodes',
     'rctv65n',
     'rctv65node',
     'rctv68',
     'rctvn60',
     'rctvn65',
     'rcvt60',
     'recurrence CTV60',
     'recurrence CTV65',
     'recurrence PTV60',
     'rgtv65',
     'rgtv65n',
     'rgtv68',
     'rgvt65node',
     'right  cochlea',
     'right  lens',
     'right ON PRV',
     'right SMG',
     'right SMG and PTV65',
     'right avoid',
     'right cochlea',
     'right cochlea AVOID',
     'right cochlea OPT',
     'right cochlea PS',
     'right eye',
     'right eye PRV',
     'right globe',
     'right globe Avoid',
     'right globe PS',
     'right lacrimal gland',
     'right lens',
     'right lens PS',
     'right level II-IVa',
     'right mandible',
     'right neck (II-IV)',
     'right neck II-V',
     "right neck II-V (+RP's)",
     'right neck ctv 54',
     'right neck ctv 60',
     'right neck nodes - 54',
     'right neck nodes ctv 54',
     'right neck nodes ctv 60',
     'right optic nerve',
     'right optic nerve PRV',
     'right orbit',
     'right parotid',
     'right parotid - PTV',
     'right parotid - PTV R 60',
     'right parotid - PTV50 rt',
     'right parotid - PTV54',
     'right parotid - PTV60',
     'right parotid - PTV60 RT',
     'right parotid - PTV70',
     'right parotid PRV',
     'right parotid and PTV',
     'right parotid and PTV54',
     'right shoulder block',
     'right sm gland',
     'right submand  gland',
     'right submand gl',
     'right submandibular g',
     'right submandibular gl',
     'right submandibular gland',
     'rightctv68',
     'rightnodes54',
     'ring',
     'ring 54',
     'ring 60',
     'ring 65',
     'ring PTV60',
     'ring ptv54',
     'ring ptv60',
     'ring ptv65 n',
     'ring ptv65 t',
     'ring ptv65n',
     'ring1',
     'ring1ptv54',
     'ring2',
     'ring2ptv54',
     'ring3',
     'ring4',
     'ring54',
     'ring54La',
     'ring54Ra',
     'ring54b',
     'ring60',
     'ring60a',
     'ring60b',
     'ring65',
     'ring65a',
     'ringA',
     'ringB',
     'rlat avoid',
     'ron',
     'rptv54',
     'rptv60',
     'rptv65n',
     'rptv65n-t1',
     'rptv65n-t1_1',
     'rptvn65',
     'rt avoid',
     'rt cochlea',
     'rt cochlea PRV',
     'rt eye',
     'rt lens',
     'rt lens PS est',
     'rt optic nerve',
     'rt parotid',
     'rt shell54',
     'rt shoulder',
     'rt shoulder block',
     'rt sub - PTVs',
     'rt submand',
     'rt submand gland',
     'rt submandibular',
     'rtctv54',
     'rtctv65nodes',
     'rtgtv65',
     'rtgtv65-2',
     'rvr',
     'scalp avoid',
     'second shell',
     'shell',
     'shell 1',
     'shell 1 - all ptv',
     'shell 2',
     'shell 54',
     'shell 54L',
     'shell 54R',
     'shell 60',
     'shell54',
     'shell60',
     'shell65',
     'shell68',
     'shoulder Blocks',
     'shoulder avoid',
     'shoulder block',
     'shoulder block L',
     'shoulder block R',
     'shoulder block lt',
     'shoulder block rt',
     'shoulder blocks',
     'shoulders',
     'skin',
     'skin density',
     'skin tidy',
     'skintidy',
     'sm gland',
     'sparing1',
     'sparing2',
     'sparing3',
     'sparing4',
     'spinal cord',
     'spinal cord / b stem',
     'spinal cord / b stem PRV',
     'spinal cord PRV',
     'spinal cord prv',
     'spinal cord sjj',
     'spinal cordPRV',
     'spinal cordPRV - PTV60',
     'spine avoid',
     'spine avoidPRV',
     'spine block',
     'submand',
     'submand gland',
     'submand left - PTV',
     'submand right  - PTV',
     'submandib gland',
     'submandib gland PRV',
     'submandibular gland',
     'submandibular glands',
     'submandibular left',
     'submandibular right',
     'sup block',
     't1',
     't1-54',
     't1-54 L',
     't1-54 R',
     't1-54-R',
     't1-54L',
     't1-60',
     't1-65',
     't1-for bolus',
     't2',
     't2-54',
     't2-54 L',
     't2-54 R',
     't2-60',
     't2-65',
     't3',
     't3 + R2 + G2 + J2 + V2 + S2 + P2 + K2 + B2',
     't3-54',
     't3-60',
     't4',
     't4-60',
     't5',
     't54',
     't60',
     't65',
     'tbol',
     'teeth',
     'teeth artefacts',
     'temp',
     'temp lobe',
     'temp- for bolus',
     'temp-for bolus',
     'temp1',
     'thyroid gland',
     'tissue',
     'tl shell54',
     'tongue CTV 60',
     'tongue PTV 60',
     'tongue base',
     'tonsil bed (GTV)',
     'tonsil bed + 15mm',
     'tonsillar bed (GTV)',
     'tonsillar bed (GTV) + 15m',
     'trgtv3',
     'tumour bed',
     'tumour bed2',
     'virtual bolus']

# Prostate cohort
prostate_plan = \
    ['15mm',
     '1MM',
     '1mm',
     '1mm shell',
     '2MM',
     'ANT AVOID',
     'ANUS',
     'ARTIFACT REGION',
     'Air',
     'Air Override',
     'Air in Rectum',
     'Air in rectum',
     'All PTV',
     'Ant Avoid',
     'Ant avoid',
     'Art Hip',
     'Art Hip PRV',
     'Art hip',
     'Artefact',
     'Artefact density override',
     'Artefacts',
     'Arterial stents',
     'Artifact',
     'Avoid',
     'Avoid THR',
     'Avoid/bowel',
     'BLADDER',
     'BLADDER (edited by KY)',
     'BLADDER - PTV60',
     'BLADDER - PTVn_6000',
     'BOWEL',
     'BOWEL BAG',
     'BOWEL PRV',
     'BOWEL+ 3 exc vess',
     'BOWEL+ 3in PTVn_6000',
     'BOWEL+3',
     'BOWEL+3 - T1',
     'BOWEL- PTVn_6000',
     'BOWEL_BAG',
     'BOWEL_PTV',
     'BULB',
     'Bladdder',
     'Bladder',
     'Bladder - PTV',
     'Bladder - PTV54',
     'Bladder - PTV60',
     'Bladder - PTV_PG',
     'Bladder - Prostate',
     'Bladder and PTV60',
     'Bladder and PTVPG',
     'Bladder in PTV',
     'Bladder in ptv60',
     'Bladder planner',
     'Block LHip',
     'Block Lt THR',
     'Block Rt THR',
     'Block artefacts',
     'Body',
     'Bowel',
     'Bowel  - PTV',
     'Bowel +3mm - vessels',
     'Bowel 3 mm Avoid',
     'Bowel+3',
     'Bowels avoid',
     'Bowels avoid - PTV',
     'Bulb',
     'COUCH',
     'CTV',
     'CTV 1',
     'CTV 2',
     'CTV PG',
     'CTV SV',
     'CTV prostate',
     'CTV-LN',
     'CTV-PG',
     'CTV-SV',
     'CTV1',
     'CTV1_1',
     'CTV2',
     'CTV_P',
     'CTV_PG',
     'CTV_SV',
     'CTV_prostate',
     'CTVln',
     'CTVn',
     'CTVn_5500',
     'Combined PTV',
     'Couch',
     'DIRECT POST BLOCK',
     'DN CTV_SV',
     'Directional block',
     'FEMORAL_HEAD_L',
     'FEMORAL_HEAD_R',
     'FEMUR_HEAD_L',
     'FEMUR_HEAD_R',
     'FOV block',
     'Fem head',
     'Femoral head left',
     'Femoral heads',
     'Femur Left',
     'Femur Left PRV',
     'Femur Left block',
     'Femur Right',
     'Femur Right Block',
     'Femur left',
     'Femurs',
     'GTV',
     'GTV1',
     'GTV2',
     'Gen Avoid',
     'Gen Block',
     'Hernia region',
     'Hip Block',
     'ICRU',
     'ICRU POINT',
     'ICRU PT',
     'ICRU Point',
     'ICRU point',
     'ICRU pt',
     'ICRUpoint',
     'ICRUpt',
     'INNER RING',
     'INNER SHELL',
     'Iliac Vessels',
     'Inner',
     'Inner Ring',
     'Inner Ring 5mm',
     'Inner Shell',
     'Inner ring',
     'Inner shell',
     'Inner shell 54',
     'JEN PROS + SV',
     'L Art Hip',
     'L Art Hip PRV',
     'L FEMORAL HEAD',
     'L FH',
     'L Femoral Head',
     'L HIP',
     'L Hiip',
     'L Hip',
     'L Hip (THR)',
     'L Hip PRV',
     'L NOF',
     'L fem head',
     'L femoral head',
     'L femur',
     'L femur head',
     'L hip',
     'LHP PRV',
     'LHR',
     'LHR PRV',
     'LHip Prosthesis',
     'LHip ProsthesisPRV',
     'LN',
     'LN CTV',
     'LN CTV - Bowel+3',
     'LN CTV - Bowel+3 - BLADDER',
     'LN CTV in prog',
     'LN GTV',
     'LN PTV',
     'LN PTV 60Gy',
     'LN PTV60',
     'LN Ring',
     'LN SHELL',
     'LN left',
     'LN ptv',
     'LN right',
     'LN ring',
     'LN2',
     'LNPTV',
     'LNPTV60',
     'LNs',
     'LT HIP',
     'LT HIP MARGIN',
     'LT LN PTV 60Gy',
     'LT LN SHELL',
     'LT fem head',
     'LT hip',
     'Left Hip',
     'Left Hip Block',
     'Left Prosthesis',
     'Left ProsthesisOPT',
     'Left femoral head',
     'Left hip',
     'Left hip block',
     'Lhip',
     'Ln PTV60',
     'Lt Avoid',
     'Lt DIRECTIONAL HIP',
     'Lt Femoral Head',
     'Lt Femur',
     'Lt Hip',
     'Lt Hip Block',
     'Lt Hip Direct block',
     'Lt Hip PRV',
     'Lt Pros',
     'Lt Prosthesis',
     'Lt Prosthesis PRV',
     'Lt Prosthetic Hip',
     'Lt THR',
     'Lt artificial hip',
     'Lt femoral Head',
     'Lt femoral head',
     'Lt hip',
     'Lt hip PRV',
     'Lt lymph nodes PTV',
     'Lt prosthesis',
     'Lt prosthesis PRV',
     'Lt prosthetic',
     'Lt prosthsis',
     'Lymph node PTV',
     'MID RING',
     'MIDDLE RING',
     'ML artefact',
     'Metal Hip',
     'Metal Hip+10mm',
     'Metal hip',
     'Metal hip PS',
     'Mid Shell',
     'Mid ring',
     'Mid shell',
     'Middle Ring',
     'Middle Shell',
     'Middle ring',
     'Middle shell',
     'Milddle shell',
     'Nail avoid',
     'OAR_bladder',
     'OAR_left hip',
     'OAR_rectum',
     'OAR_right hip',
     'OUTER RING',
     'OUTER SHELL',
     'Outer Ring',
     'Outer Ring 15mm',
     'Outer Shell',
     'Outer ring',
     'Outer shell',
     'PB',
     'PENILE BULB',
     'PENIS BLOCK',
     'PG RIng',
     'PG Ring',
     'PG_PTV',
     'POST  AVOID',
     'POST AVIOD',
     'POST AVOID',
     'POST BLK',
     'POST BLOCK',
     'POST DIRECT BLOCK',
     'PROS',
     'PROS+SV',
     'PROS+sv',
     'PROSTATE',
     'PROSTATE+SV',
     'PROSTATE+sv',
     'PROSTHESIS',
     'PROSTHESIS PRV',
     'PRV',
     'PRV BOWEL',
     'PRV Lt Hip',
     'PRV Lt Prosthesis',
     'PRV Lt artificial hip',
     'PRV Pros ext AP',
     'PRV Rt Hip',
     'PRV Rt Prosthesis',
     'PRV Rt THR',
     'PRV lt metal hip',
     'PRV rt artificial hip',
     'PRV rt metal hip',
     'PRVLt Pros',
     'PRVRt pros',
     'PS PTV SV - PG',
     'PTV',
     'PTV  74',
     'PTV 1',
     'PTV 1 60',
     'PTV 2',
     'PTV 48',
     'PTV 54',
     'PTV 55',
     'PTV 59.2',
     'PTV 60',
     'PTV 60 Gy',
     'PTV 60Gy',
     'PTV 6OGy',
     'PTV 74',
     'PTV 74 Gy',
     'PTV 74Gy',
     'PTV LN',
     'PTV LN 55',
     'PTV LN Lt',
     'PTV LN Rt',
     'PTV LNs',
     'PTV PG',
     'PTV PG + PTV SV',
     'PTV PG RING',
     'PTV PG and Rectum',
     'PTV SV',
     'PTV SV + PTV PG',
     'PTV SV INNER RING',
     'PTV SV OUTER RING',
     'PTV Shell',
     'PTV ring 1',
     'PTV ring 2',
     'PTV shell',
     'PTV-LN',
     'PTV1',
     'PTV1 (60)',
     'PTV1 (60Gy)',
     'PTV1 + LNPTV',
     'PTV1 10mm post',
     'PTV1 45.6',
     'PTV1 54',
     'PTV1 54 Gy',
     'PTV1 59.2Gy',
     'PTV1 5mm post',
     'PTV1 60',
     'PTV1 60Gy',
     'PTV1 SHELL',
     'PTV1(54)',
     'PTV1(60)',
     'PTV154Gy',
     'PTV160',
     'PTV2',
     'PTV2 (74)',
     'PTV2 (74Gy)',
     'PTV2 54.7',
     'PTV2 60',
     'PTV2 60Gy',
     'PTV2 74',
     'PTV2 74Gy',
     'PTV2(60)',
     'PTV2(74)',
     'PTV260Gy',
     'PTV274',
     'PTV3',
     'PTV3 57',
     'PTV45.6',
     'PTV48',
     'PTV54',
     'PTV54.6',
     'PTV54Gy',
     'PTV55',
     'PTV57',
     'PTV59',
     'PTV59.2',
     'PTV60',
     'PTV60 + LNs',
     'PTV60 ln + presacral',
     'PTV60Gy',
     'PTV60new',
     'PTV70',
     'PTV74',
     'PTV74Gy',
     'PTVPG',
     'PTVPG74',
     'PTVSV',
     'PTVSV60',
     'PTV_59.2',
     'PTV_60Gy',
     'PTV_74',
     'PTV_74Gy',
     'PTV_LN',
     'PTV_PG',
     'PTV_PG2',
     'PTV_SV',
     'PTV_SV + PTV_PG',
     'PTV_SV + PTV_prost',
     'PTV_prostate',
     'PTVn_6000',
     'PTVp_7100',
     'PTVp_7400',
     'PTVpsv_60- 71',
     'PTVpsv_6000',
     'PTVshell',
     'Pelvic LNs',
     'Pelvic LNsPTV',
     'Pelvic floor muscles',
     'Penile Bulb',
     'Penile bulb',
     'Periferal Shell',
     'Perifferal shell',
     'Pin',
     'Post  avoid',
     'Post Avoid',
     'Post Block',
     'Post Bock',
     'Post Direct avoid',
     'Post avoid',
     'Post block',
     'Post direct avoid',
     'Post direct block',
     'Post rectum avoid',
     'PostAvoid',
     'Pr',
     'Pr+sv',
     'Pro',
     'Pros',
     'Pros  base',
     'Pros &SV',
     'Pros + SVs',
     'Pros sv',
     'Pros&SVs',
     'Pros+base',
     'Pros+base sv',
     'Pros+base_1',
     'Pros+sv',
     'Pros+svSGR',
     'Pros+sv_1',
     'ProsSVs',
     'Prosate',
     'Prosate and SVs',
     'Prosta',
     'Prosta+sv',
     'Prostate',
     'Prostate  SVs',
     'Prostate & SV',
     'Prostate &SV',
     'Prostate (CTV2)',
     'Prostate + Rsv',
     'Prostate + SV',
     'Prostate + SV (CTV1)',
     'Prostate + SVs',
     'Prostate + base sv',
     'Prostate + seminal vesicles',
     'Prostate + sv',
     'Prostate +SV',
     'Prostate 1',
     'Prostate 1 + SV',
     'Prostate CTV',
     'Prostate Only',
     'Prostate SVs',
     'Prostate and SVs',
     'Prostate and sv',
     'Prostate base',
     'Prostate bed',
     'Prostate only',
     'Prostate sv',
     'Prostate&SV',
     'Prostate&SVs',
     'Prostate&sv',
     'Prostate+ sv',
     'Prostate+SV',
     'Prostate+SVs',
     'Prostate+SVs (CTV1)',
     'Prostate+base',
     'Prostate+base sv',
     'Prostate+basesv',
     'Prostate+bs',
     'Prostate+sv',
     'Prostate+svs',
     'Prostate/SV',
     'Prostate/SVs',
     'Prostate/sv',
     'Prostate_1',
     'Prostatesv',
     'Prosthesis',
     'Prosthesis avoid',
     'R Art Hip',
     'R Art Hip PRV',
     'R FEMORAL HEAD',
     'R FH',
     'R Fem head',
     'R Femoral Head',
     'R HIP',
     'R Hip',
     'R NOF',
     'R fem head',
     'R femoral head',
     'R femur',
     'R femur head',
     'R head fem',
     'R hip',
     'R1',
     'RECTAL AVOID',
     'RECTAL BLOCK',
     'RECTUM',
     'RECTUM (edited by KY)',
     'RECTUM - PTV60',
     'RECTUM outside PTV',
     'RECTUM1',
     'RECTUM2',
     'RECTUM_A_ANUS',
     'RHP PRV',
     'RING',
     'RING 1',
     'RING 2',
     'RING OUTER',
     'RING PG',
     'RING PTVp',
     'RING PTVpsv',
     'RING1',
     'RING2',
     'RING_PTVp',
     'RING_PTVpsv',
     'RT HIP',
     'RT HIP MARGIN',
     'RT Hip',
     'RT LN PTV 60Gy',
     'RT LN SHELL',
     'RT fem head',
     'RT hip',
     'RVR',
     'Rectal Avoid',
     'Rectal Block',
     'Rectal avoid',
     'Rectal block',
     'Rectum',
     'Rectum - PTV',
     'Rectum - PTV PG',
     'Rectum - PTV54',
     'Rectum - PTV60',
     'Rectum Avoid',
     'Rectum Block',
     'Rectum and PTV PG',
     'Rectum and PTV60',
     'Rectum and PTVPG',
     'Rectum avoid',
     'Rectum block',
     'Rectum in PTV',
     'Rectum in PTV54',
     'Rectum in PTV60',
     'Rectum in PTV74',
     'Rectum-PTV',
     'Rectum-PTV60',
     'RectumBlock',
     'Rfemur',
     'Right Hip',
     'Right Prosthesis',
     'Right ProsthesisOPT',
     'Right femoral head',
     'Ring',
     'Ring  1',
     'Ring 1',
     'Ring 1 Pros',
     'Ring 1cm',
     'Ring 2',
     'Ring 2 Pros',
     'Ring 2cm',
     'Ring 60',
     'Ring 74',
     'Ring Inner',
     'Ring LN',
     'Ring LN Lt',
     'Ring LN Rt',
     'Ring Outer',
     'Ring PG',
     'Ring PTV54',
     'Ring PTV60',
     'Ring SV',
     'Ring inner',
     'Ring outer',
     'Ring1',
     'Ring10mm',
     'Ring1cm',
     'Ring2',
     'Ring2.5cm',
     'Ring25mm',
     'Ring2cm',
     'Ring3',
     'Ring60',
     'Ring71',
     'Ring74',
     'RingLNPTV',
     'RingPG',
     'RingPTV60Gy',
     'RingPTV74Gy',
     'Ring_PTVp',
     'Ring_PTVpsv',
     'Rt Art Hip',
     'Rt Art Hip PRV',
     'Rt Art HipPRV',
     'Rt Art hip',
     'Rt Avoid',
     'Rt DIrectional Hip',
     'Rt Femoral Head',
     'Rt Hip',
     'Rt Hip Block',
     'Rt Hip PRV',
     'Rt Prosthesis',
     'Rt ProsthesisOPT',
     'Rt THR',
     'Rt fem head',
     'Rt femoral Head',
     'Rt femoral head',
     'Rt femur',
     'Rt hip',
     'Rt hip_',
     'Rt hp',
     'Rt lymphnodes PTV',
     'Rt pros',
     'Rt prosthesis',
     'Rt prosthesis PRV',
     'Rt prosthetic hip',
     'Rt prosthetic hip2',
     'Rthip',
     'S1',
     'S2',
     'S3',
     'SHELL',
     'SHELL 1',
     'SHELL 2',
     'SHELL 60Gy',
     'SHELL 74Gy',
     'SHELL INNER',
     'SHELL NODES',
     'SHELL OUTER',
     'SHELL PTV1',
     'SHELL PTV2',
     'SHELL1',
     'SHELL10',
     'SHELL2',
     'SHELL20',
     'SHELL74',
     'SHELLinner',
     'SHELLouter',
     'SKIN',
     'SKIN_SP',
     'SV',
     'SV + Prostate',
     'SV CTV',
     'SV ctv',
     "SV's",
     'SVs',
     'Seminal vesicles',
     'Shell',
     'Shell  60',
     'Shell 1',
     'Shell 2',
     'Shell 60',
     'Shell 60Gy',
     'Shell 74Gy',
     'Shell Inner',
     'Shell Outer',
     'Shell PG',
     'Shell SV',
     'Shell outer',
     'Shell1',
     'Shell2',
     'ShellPTV1',
     'ShellPTV2',
     'Sigmoid',
     'Sigmoid Colon',
     'Sigmoid colon',
     'Sigmoid colon in PTV',
     'Sigmoid colon out PTV',
     'Skin',
     'Skin_1',
     'Small Bowel',
     'Small Bowel - PTV',
     'Small bowel',
     'Small bowels',
     'Sv',
     'Svs',
     'T1',
     'T2',
     'T3',
     'T4 + PTVSV',
     'TISSUE',
     'TN1',
     'Tp',
     'Tp+5mm',
     'Tpsv',
     'URETHRAL BULB',
     'Urethral Bulb',
     'VESSELS',
     'VESSELS+6',
     'Vessels',
     'Vessels+6',
     'Vessels+6 - BOWEL+3',
     'Vessels+6 - BOWEL+3 - BLADDER',
     'Vessels2',
     'Vessles',
     'Vessles2',
     'abdo apron',
     'air',
     'air in PTV60',
     'air in PTV74',
     'air in rectum',
     'all PTV',
     'ant avoid',
     'artefact',
     'artefact in bone',
     'artefacts',
     'artifact',
     'avoid',
     'avoid sb',
     'base sv',
     'bladder',
     'bladder - T1',
     'bladder in ptv',
     'bladderkw',
     'block',
     'body',
     'bowel',
     'bowel exclusion zone',
     'bulb',
     'combined PTVs',
     'couch',
     'ctv',
     'ctv prostate',
     'ctv seminal vesicles',
     'ctv sv',
     'ctv1',
     'ctv2',
     'cvt2',
     'density',
     'density 1',
     'densityone',
     'direct post block',
     'femoral head',
     'femoral head_lt',
     'femoral head_rt',
     'gas',
     'gtv2',
     'heads of femori',
     'hip l',
     'hip prv',
     'hip r',
     'icru',
     'icru point',
     'icru pt',
     'ing hernia',
     'inner ring',
     'inner shell',
     'innner ring',
     'l fem head',
     'l femoral head',
     'l hip',
     'lT HIP',
     'large bowel',
     'left femoral head',
     'left femur',
     'left head of femur',
     'left hip',
     'left hip PRV',
     'left hip prosthesis',
     'low density artefact',
     'lt fem head',
     'lt hip',
     'lt metal hip',
     'lymph node PTV',
     'lymph nodes',
     'lymph nodes left',
     'lymph nodes right',
     'metal',
     'metal hip',
     'metal hipOPT',
     'metal pin',
     'mid avoid',
     'mid ring',
     'mid shell',
     'middie shell',
     'middle ring',
     'middle shell',
     'missing tissue',
     'nail',
     'node ptv',
     'node shell inner',
     'node shell outer',
     'nodes CTV',
     'nodesPTV',
     'not used1',
     'not used2',
     'not used3',
     'outer',
     'outer ring',
     'outer shell',
     'pelvic node CTV',
     'pelvic node PTV',
     'pelvic nodes',
     'penile bulb',
     'penis block',
     'pennis block',
     'pin',
     'pin PRV',
     'pinPRV',
     'post',
     'post  avoid',
     'post Avoid',
     'post Block',
     'post avoid',
     'post block',
     'post direct avoid',
     'post direct block',
     'post rect avoid',
     'post rectum avoid',
     'pr',
     'pr+sv',
     'presacral',
     'pros',
     'pros+base',
     'pros+sv',
     'prostate',
     'prostate & SV',
     'prostate & SV (KY)',
     'prostate &SV',
     'prostate (KY)',
     'prostate + SV',
     'prostate + SVs',
     'prostate CTV',
     'prostate and SV',
     'prostate and SVs',
     'prostate and sv',
     'prostate bed',
     'prostate bed2',
     'prostate ctv',
     'prostate only',
     'prostate sv',
     'prostate&sv',
     'prostate+sv',
     'prostate/SV',
     'prostate/sv',
     'prosthesis',
     'prosthesisPRV',
     'proxSeminal vesicles CTV',
     'ptv1',
     'ptv1 54',
     'ptv2',
     'ptv3',
     'ptv59.2',
     'ptv60',
     'ptv74',
     'pubic CTV',
     'pubic PTV54',
     'pubic ring',
     'pubic symphysis met',
     'r  hip',
     'r FH',
     'r fem head',
     'r femoral head',
     'r hip',
     'rT HIP',
     'rec post',
     'rect block',
     'rectal Block',
     'rectal avoid',
     'rectal block',
     'rectum',
     'rectum - PTV',
     'rectum - PTV54',
     'rectum - PTV60',
     'rectum - T1',
     'rectum Avoid',
     'rectum and PTV60',
     'rectum avoid',
     'rectum block',
     'rectum in PTV',
     'rectum in PTV60',
     'rectum in PTV74',
     'rectum planner',
     'rectum planner  - PTV PG',
     'rectum planner  and PTV PG',
     'rectum sort of',
     'rectum_block',
     'rhip',
     'right femoral head',
     'right femur',
     'right head of femur',
     'right hip',
     'right hip PRV',
     'right hip prosthesis',
     'ring',
     'ring 1',
     'ring 2',
     'ring in',
     'ring out',
     'ring1',
     'ring2',
     'rt artificial hip',
     'rt fem head',
     'rt femoral head',
     'rt hip',
     'rt metal hip',
     'rvr',
     'seed1',
     'seed2',
     'seed3',
     'seminal vesicle CTV',
     'seminal vesicle ctv',
     'seminal vesicles',
     'seminal vesicles CTV',
     'shadow',
     'shell',
     'shell - PTV1 + LNPTV',
     'shell 1',
     'shell 2',
     'shell1',
     'shell1mm',
     'shell2',
     'skin',
     'small bowel',
     'small bowels',
     'sv',
     'sv ctv',
     't1',
     't1- PG',
     't2',
     't2- PG',
     't3',
     't3- PG',
     't4',
     't4- PG',
     't5',
     't5- PG',
     'target',
     'temp',
     'tissue',
     'tumour gtv',
     'unit density',
     'urethra at apex',
     'urethral bulb',
     'vessels',
     'vessels + 0.7cm - OARs',
     'vessels and 0.7cm',
     'vessels2']
