# Workflow for building docker image and pushing to GitHub Container Registry
# based on:
#     https://codesalad.dev/blog/push-to-github-container-registry-using-github-actions-7

name: docker

on: [push, pull_request]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run tests.
        run: |
          cd tests
          pytest -vv
          cd ..
      - name: Login to GitHub Container Registry
        if: github.repository == 'scikit-rt/scikit-rt' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push Docker Image
        if: github.repository == 'scikit-rt/scikit-rt' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: docker/build-push-action@v4
        with:
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest
